### ISSUE TITLE
When will Release version 4 of the Node.JS programming model for Azure Functions?

### ISSUE THREAD

**Issue by sunil-bagde** [Azure/azure-functions-nodejs-library#101]
Hello Azure fn team,

about V4 programming model when will be get stable? do you have any release plan?

We are writing new app with (50-75) functions with other Azure Service bus, SignalR and redis cache.

What would be you advise, should we start with v4, and in upcoming months it will be released?

Regards

**Comment by ejizba** [comment]
Hello, you can see our timeline estimates in our Roadmap here: https://github.com/Azure/azure-functions-nodejs-library/wiki/Roadmap
