### ISSUE TITLE
Tutorial HttpTrigger typescript V4 example doesn't register function locally

### ISSUE THREAD

**Issue by niole** [Azure/azure-functions-nodejs-library#102]
I created a function with the [http trigger example](https://github.com/Azure/azure-functions-nodejs-library/tree/v4.x#typescript). I ran it via the command line on a mac with `func start --verbose`.

 I get the message `1 functions found, 0 functions loaded, Generating 0 job function(s), No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddT
imers(), etc.).`

#### Investigative information
local.settings.json:
```
{
  "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
}
```
trigger:
```
import { app, InvocationContext, HttpRequest, HttpResponseInit } from "@azure/functions";

export async function httpTrigger1(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`);

    const name = request.query.get('name') || await request.text() || 'world';

    return { body: `Hello, ${name}!` };
};

app.http('httpTrigger1', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: httpTrigger1
});

```
 I hit the trigger at curl localhost:7071/api/httpTrigger1 and the server receives the request, but ofc it says "No HTTP routes mapped".

Please provide the following:

- Timestamp: Tue Jun 06 2023 10:25:12 GMT-0700 (Pacific Daylight Time)
- Function App name: none, we are running locally only
- Function name(s) (as appropriate):httpTrigger1
- Invocation ID:
- Region:none, we are running locally only

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by pmosconi** [comment]
Hi, I was able to fix this by updating the Core Tools to latest version available here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools

**Comment by ejizba** [comment]
Hi @niole, sorry for the delay. Did updating the core tools version by chance fix this for you as well? If not, could you copy the logs from `func start` here?
