### ISSUE TITLE
The `HttpTriggerOptions.route` property needs better documentation 

### ISSUE THREAD

**Issue by anddoutoi** [Azure/azure-functions-nodejs-library#103]
Figuring out what patterns and syntax the `route` property supports is hard. Finding clear documentation is close to impossible.

- [Customize the HTTP endpoint](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cin-process%2Cfunctionsv2&pivots=programming-language-javascript#customize-the-http-endpoint) is far from satisfactory
- [Route Constraints](https://learn.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2#constraints) fill in some gaps but still leaves out for implicit interpretations

I think that a page like [Express routing](https://expressjs.com/en/guide/routing.html) but for azure functions/static web apps API routing is needed.

**Comment by ejizba** [comment]
We got more feedback that this is confusing, so bumping priority a bit

https://github.com/MicrosoftDocs/azure-docs/issues/112725

Especially for model v4, it seems like you should be able to use route parameters like this:
```
app.http('httpTrigger1/{id}', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: httpTrigger1
});
```

But you have to do this:
```
app.http('httpTrigger1', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    route: 'httpTrigger1/{id}',
    handler: httpTrigger1
});
```

**Comment by ejizba** [comment]
Between now and my last comment we added model v4 samples to the existing docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cin-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-javascript#customize-the-http-endpoint

Further improvements will be tracked with:
https://github.com/Azure/azure-functions-nodejs-library/issues/167
