### ISSUE TITLE
Unknown ParameterBindingType

### ISSUE THREAD

**Issue by agkreddy** [Azure/azure-functions-nodejs-library#109]
I am using queue output binding in one of my azure function, at certain conditions I need to skip adding messages to queue. Following is throwing up when we skip adding message to queue

Unknown ParameterBindingType

**Comment by ejizba** [comment]
Hi @agkreddy, I believe we fixed this already - can you try updating your `@azure/functions` npm package to version `v4.0.0-alpha.10` or higher

https://github.com/Azure/azure-functions-nodejs-library/releases/tag/v4.0.0-alpha.10

**Comment by agkreddy** [comment]
@ejizba Thanks for the quick turn around. Updating from v4.0.0-alpha.7to v4.0.0-alpha.10 helps
