### ISSUE TITLE
Node V4 Extra output Sendgrid binding - Long wait time for processing request

### ISSUE THREAD

**Issue by agkreddy** [Azure/azure-functions-nodejs-library#112]
**Use case** Use azure function to send bulk email using Sendgrid binding

**Approach** Prepare a format that is supported by Sendgrid and bind that to Sendgrid bindings by using context.extraOuptut

**Function Used** HTTP azure function which gets invoked by web application

**Problem** If a request has been made to send out 100 emails it is taking more than a minute to process because of synchronous extraOuptut. Even with the queues it is the same.

**Solution Looking for** We are looking for solution to send emails in an asynchronous approach(Leave and forgot).

**Comment by ejizba** [comment]
Hi, could you share sample code for this?
