### ISSUE TITLE
Pushing batches to queue using  **context.extraOutput** 

### ISSUE THREAD

**Issue by agkreddy** [Azure/azure-functions-nodejs-library#113]
**Problem Statement** Need to push batches to queue at intervals, but **context.extraOutput** is only pushing last set of the batch to queue

**Example:** I have 100 messages to be sent to Sendgrid for mailing. Due to drops with bulk processing of all messages at once, I need to push 20 messages to queue rather than all 100 at once  and process as batches.

**Scenario** When azure function is migrated from V3 to V4 **context.binding** has been replaced with **context.extraOutput** where I am pushing set of  batch messages to queue. With **context.binding** I can send batches to queue at intervals but with **context.extraOutput** I could not able to do.

Is there a approach sending batches to queue at regular intervals rather than all at once using **context.extraOutput** which is taking long times to process.

**Comment by ejizba** [comment]
Could you share sample code in v3 that is using batching and sample code in v4 that isn't working? The name `binding` vs `extraOutput` changed, but the behavior should largely be the same. To be honest, I'm a little confused how you got batching to happen in v3 as I didn't think that was supported

**Comment by MaddyTP** [comment]
Following.  I too am attempting to batch results from a long running process.

**Comment by ejizba** [comment]
As mentioned above, I don't think this was ever supported in the old v3 model. If you need to send send batches, the recommended approach (for either model) would be to use the service-bus sdk directly https://www.npmjs.com/package/@azure/service-bus
