### ISSUE TITLE
No HTTP Triggers found when using MongoDB connection pooling

### ISSUE THREAD

**Issue by lesofl** [Azure/azure-functions-nodejs-library#117]
#### Investigative information

**For Azure Functions v4 (preview)**

An error seems to occur solely when deploying to Azure Functions when using MongoDB pooled connections. Testing functions locally will show all the required functions and will work entirely as intended however deploying via VSCode through Azure Functions extension will always produce the error of no HTTP Triggers found. 

First noticed this issue around 2 weeks ago and after removing each line of code one by one, I was able to pinpoint it to the MongoDB connection initialisation. I have been unable to deploy the function app from VSCode since there and have circumvented this using Github Actions, which seems to work perfectly fine. I have tried downgrading azure functions version and also mongodb version to previous versions. Doesn't seem to fix the issue.

I have not tried using commonjs yet as most of my code is using es6 and it was working perfectly fine a few weeks ago until one day I deployed and realised all my http triggers had been wiped.

I do apologise if below information is not clear enough, first time submitting a bug so please do let me know if there's any more information required.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create new Function App with v4 Preview and create first http function.
2. npm i install mongodb
3. Place MongoDB connection pooling code outside of the function that requires it.
4. Attempt to deploy code to Function App

#### Expected behavior

Should deploy all HTTP trigger functions to Azure Functions

#### Actual behavior

Shows that there are No HTTP Triggers and when checking Azure Function in web portal, all previous functions are removed as the new deployment deletes all existing data.

#### Failing Version
![image](https://github.com/Azure/azure-functions-nodejs-library/assets/124645288/161210e9-9da1-43dc-a0d3-e895ac4e0aba)

failing code
```node
import { app } from "@azure/functions";
import { MongoClient } from "mongodb";

const uri = process.env["CUSTOMCONNSTR_MONGODB_CONNECTION_STRING"];
const client = new MongoClient(uri, {
	useNewUrlParser: true,
	useUnifiedTopology: true,
});

app.http("httpTrigger1", {
	methods: ["GET", "POST"],
	authLevel: "anonymous",
	handler: async (request, context) => {
		context.log(`Http function processed request for url "${request.url}"`);

		const name = request.query.get("name") || (await request.text()) || "world";

		// MongoDB Function
		const database = client.db(process.env.MONGODB_DATABASE);
		const result = await database.collection("collection").findOne({
			name: "name",
		});

		return { body: `Hello, ${name}!` };
	},
});
```

This version of code is also working when debugging locally. I am able to call the function and have it execute properly.

![image](https://github.com/Azure/azure-functions-nodejs-library/assets/124645288/6ae4ab9d-7d26-4838-af32-6f62e1acabb3)

#### Working Version
![image](https://github.com/Azure/azure-functions-nodejs-library/assets/124645288/1d4c906c-ffb7-47d5-ae09-a268d4e1f9b0)

working code
```node
import { app } from "@azure/functions";
import { MongoClient } from "mongodb";

app.http("httpTrigger1", {
	methods: ["GET", "POST"],
	authLevel: "anonymous",
	handler: async (request, context) => {
		context.log(`Http function processed request for url "${request.url}"`);

		const name = request.query.get("name") || (await request.text()) || "world";

		const uri = process.env["CUSTOMCONNSTR_MONGODB_CONNECTION_STRING"];
		const client = new MongoClient(uri, {
			useNewUrlParser: true,
			useUnifiedTopology: true,
		});

		// MongoDB Function
		const database = client.db(process.env.MONGODB_DATABASE);
		const result = await database.collection("collection").findOne({
			name: "name",
		});

		return { body: `Hello, ${name}!` };
	},
});
```

#### Known workarounds

I am able to get around this problem by using Github Actions.

Also as shown above, I am able to get around the problem if I continually add the MongoClient instantiation string inside the function and not outside of it.

#### Related information 

Provide any related information

package.json.
```node
{
	"name": "blank",
	"version": "1.0.0",
	"description": "",
	"type": "module",
	"scripts": {
		"start": "func start",
		"test": "echo \"No tests yet...\""
	},
	"dependencies": {
		"@azure/functions": "^4.0.0-alpha.7",
		"mongodb": "^5.7.0"
	},
	"main": "src/functions/*.js"
}
```

The code here is entirely from creating a new httpTrigger using the Azure Functions extension, only the MongoDB connection pooling code has been added.

There are absolutely no errors observed. Everything works perfectly fine using either method when debugging, only during deployment does it decide it doesn't like putting the client instantiation outside for whatever reason and can't find any HTTP triggers.

**Comment by ejizba** [comment]
> There are absolutely no errors observed.

I just want to call out that we have a known pain point where errors aren't showing up properly. We have made some changes so that they will show up in app insights, but that hasn't rolled out in Azure yet. This was tracked by https://github.com/Azure/azure-functions-nodejs-library/issues/85

> as shown above, I am able to get around the problem if I continually add the MongoClient instantiation string inside the function and not outside of it.

To be honest, I'm not sure why this is necessary. Does it work if you put the `process.env` line outside the function but the `new MongoClient` line inside? I'm curious which line is causing the problem. Is `CUSTOMCONNSTR_MONGODB_CONNECTION_STRING` an app setting? If so, it _should_ be defined regardless or where you access it, but maybe there's a bug there.

**Comment by lesofl** [comment]
Thanks, I was aware that there was an issue with errors not showing up but thought this might have been resolved since that issue had been closed and to test for deployment errors I would usually just run a local build and if it was successful, then deployment would be suitable.

I have also tried debugging exactly which line causes this issue and found that the issue exists solely with how the ```process.env.CUSTOMCONNSTR_MONGODB_CONNECTION_STRING``` is being added. There is an exact match inside my ```local.settings.json``` with this parameter.

If I copy and paste the plaintext connection string in as the ```uri```, it'll successfully detect my http trigger. Using any ```process.env``` variable seems to break it however.

This is my current testing local.settings.json
```
{
	"IsEncrypted": false,
	"Values": {
		"AzureWebJobsStorage": "",
		"FUNCTIONS_WORKER_RUNTIME": "node",
		"AzureWebJobsFeatureFlags": "EnableWorkerIndexing",
		"CUSTOMCONNSTR_MONGODB_CONNECTION_STRING": "mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin"
	}
}
```

Specifically the ```uri``` in this code snippet seems to break if a ```process.env``` variable is used instead of a string. Perhaps a problem with the instantiation of the actual environment variable.

working:
```
const uri = "mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin"; 
```

non-working: 
```
const uri = process.env.CUSTOMCONNSTR_MONGODB_CONNECTION_STRING;
```

**Comment by ejizba** [comment]
Can you confirm is `CUSTOMCONNSTR_MONGODB_CONNECTION_STRING` defined as an app setting in Azure?

**Comment by lesofl** [comment]
Hey @ejizba, 

I was able to resolve this issue by removing my database connection string as specifically a database connection string to just an application setting. Not exactly sure why this caused this problem but is working perfectly fine now.

Thanks for your help.
