### ISSUE TITLE
Question: Middleware or beginningware documentation

### ISSUE THREAD

**Issue by core-dev-out** [Azure/azure-functions-nodejs-library#118]
I see from this [PR](https://github.com/Azure-Samples/contoso-real-estate/pull/231/) in Contoso Real Estate, that I can use middleware in a Function, but is there a way to add code that runs before any of the functions are called? 

This would be for db connections or other start up tasks.

**Comment by ejizba** [comment]
Hi @core-dev-out we are tracking this in https://github.com/Azure/azure-functions-nodejs-library/issues/7, and @hossam-nasr has a PR out here: https://github.com/Azure/azure-functions-nodejs-library/pull/115
