### ISSUE TITLE
[Tracking] Make v4 entry point failures more obvious

### ISSUE THREAD

**Issue by smolattack** [Azure/azure-functions-nodejs-library#119]
To reproduce, create a function app in uksouth with a runtime of node v18. Create a new TypeScript http tirgger function (`func new`) and use the following commands to publish the function function

```bash
npm i @azure/functions@4.0.0-alpha.11 --save-exact
npm run build
func azure functionapp publish <name of your function app>
Getting site publishing info...
Creating archive for current directory...
Uploading 3.33 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in <name of your function app>:
    httpTrigger - [httpTrigger]
        Invoke url: <name of your function app>.azurewebsites.net/api/httptrigger

```

## Repro

next, add the cosmos sdk to your project
```bash
npm i @azure/cosmos@3.17.3 --save-exact
```

open httpTrigger.ts and just add the following two lines 

```ts
import { CosmosClient } from "@azure/cosmos";
const client = new CosmosClient({ endpoint: "", key: "" });

```

Rebuild the project and try to redeploy
```bash
npm run clean && npm run build
func azure functionapp publish <name of your function app>
Getting site publishing info...
Creating archive for current directory...
Uploading 3.22 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in <name of your function app>:

```

Notice how this time, there are no functions listed even though the deployment is considered successful. Furthermore, going to Azure Portal -> your function app -> Functions blade -> you should see there are no functions listed (you would see your function if you just remove the cosmos sdk code, rebuild and redeploy).

## context
```bash
cat /etc/issue
Pop!_OS 22.04 LTS \n \l

node --version
v18.16.1

func --version
4.0.5198

```
package.json
```json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "dist/src/functions/*.js",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "clean": "rimraf dist",
    "prestart": "npm run clean && npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/cosmos": "3.17.3"
  },
  "devDependencies": {
    "@types/node": "18.x",
    "azure-functions-core-tools": "4.0.5198",
    "rimraf": "^5.0.0",
    "typescript": "^4.9.5"
  }
}

````

## what should happen
We should be able to use the cosmos sdk in a v4 node@18 function. At the very least, failures should be obvious and not silent.

**Comment by smolattack** [comment]
I get this issue with other packages as well such as axios

**Comment by ejizba** [comment]
Hi @smolattack - sorry for the delay. Moving this to a more node.js-specific repo

> At the very least, failures should be obvious and not silent.

Unfortunately we have a known pain point around this. We have made some changes, but it hasn't rolled out in Azure yet. Tracked by https://github.com/Azure/azure-functions-nodejs-library/issues/85

Were you able to figure out your errors around the cosmos client and axios? You can either wait for our changes to roll out in Azure (in which case you should be able to see the errors), or you can share your app name with me and I can take a look. See here for how to share the app name privately: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by smolattack** [comment]
Hi @ejizba here are the details for a function that did deploy. There should have been two function  (not sure why the other function did not deploy)
invocation id: c1e142a5-530e-4d69-b1df-467e79ee60c6
2023-08-14T18:05:10Z
UK South

**Comment by ejizba** [comment]
Thanks @smolattack. The error I'm seeing for that app is `Worker was unable to load entry point 'dist/src/functions/*.js': Cannot find module 'arktype'`

Hopefully that helps you investigate. Like I said, we have a change rolling out to hopefully help you see this error yourself in the future

**Comment by smolattack** [comment]
Ok thanks that helps. Can I keep this issue open so that I can get diagnostic messages if I run into more problems?

**Comment by ejizba** [comment]
Yeah that's fine for now. I'll comment and close this issue once https://github.com/Azure/azure-functions-nodejs-library/issues/85 finishes rolling out, which should be in the next couple of weeks.

**Comment by smolattack** [comment]
@ejizba I need help with a deployment please. No functions deploy this time so can't use option 1 to obtain the invocation id. Option 2 gives me 404 and nothing appears on the logs either. I'm on runtime 4.24.4.4 if that means anything.

Edit: I noticed these entries in the logs.
2023-09-04T21:46:32Z   [Information]   Loading functions metadata
2023-09-04T21:46:32Z   [Information]   Reading functions metadata
2023-09-04T21:46:32Z   [Information]   1 functions found
2023-09-04T21:46:32Z   [Information]   0 functions loaded
2023-09-04T21:46:32Z   [Information]   Loading functions metadata
2023-09-04T21:46:32Z   [Information]   Reading functions metadata
2023-09-04T21:46:32Z   [Information]   1 functions found
2023-09-04T21:46:32Z   [Information]   0 functions loaded

**Comment by ejizba** [comment]
For option 2 it's expected to return 404. You just have to give me the guid and I'll be able to find that guid in our backend logs.

I assume this is a different app from above? Seems like the above app is on host 4.25 now, meaning you should be able to see errors in the `traces` table of your application insights. Also add the app setting `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` set to `1` and that should ensure you get all errors.

**Comment by smolattack** [comment]
So where is this documented? What does FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR mean? What query under traces should I use (I use the same application insights for multiple function apps)

**Comment by ejizba** [comment]
I would do something like this to see all errors:

```
traces
| where cloud_RoleName =~ "<app name>"
| where timestamp > ago(1d)
| where severityLevel > 2
```

If that returns too many results, you could add
```
| where message startswith "Error: Worker was unable to load entry point"
```

The app setting isn't documented yet. I'll add some docs once 4.25 finishes rolling out. It's done on windows, but still rolling out on Linux.


The app setting specifically helps v4 apps that get "No functions found". Even with our recent improvements, not all entrypoint errors will show up in app insights. This is because we were limited in what we could do without breaking existing apps (particularly model v3 apps). The app setting is a temporary measure recommended for v4 model apps to make sure you can see _all_ entry point errors in your app insights. Starting with Node.js v20, this setting will no longer be necessary and it will just be the default behavior (discussed [here](https://github.com/Azure/azure-functions-nodejs-worker/issues/697)).

**Comment by smolattack** [comment]
@ejizba Could I get some help with a deployment failure? The app that's failing is on 4.24. I've even created a new function app which is also on this old runtime.
testing-deployment-serverless
UK South
8AM UTC

Is there a way to force the runtime to upgrade (linux/nodejs)?

**Comment by ejizba** [comment]
> Is there a way to force the runtime to upgrade (linux/nodejs)?

Unfortunately, no. Linux consumption is the only OS/sku left and it's been a bit slow to roll out for various reasons. Hopefully it should be done soon.

Here's what I see:

> Worker was unable to load entry point 'dist/src/functions/createFileItem.js': Environment not correctly initialized: COSMOS_ACCOUNT_NAME must be defined,COSMOS_KEY must be defined,COSMOS_DATABASE must be defined,ccadminservicebus_SERVICEBUS must be defined

**Comment by ejizba** [comment]
4.25 is done rolling out by this point. We also added some docs related to this stuff:
- A general troubleshooting guide: https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-troubleshoot?pivots=nodejs-model-v4
- Docs on the `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` app setting: https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_node_block_on_entry_point_error
