### ISSUE TITLE
Cannot load jwks-rsa in Azure functions 

### ISSUE THREAD

**Issue by bkhajuri** [Azure/azure-functions-nodejs-library#121]
#### Investigative information

Please provide the following:

- Timestamp:
- avoidRead3
- avoidread3
- Invocation ID: 73e449145f2b47f6b251ee2d77ca2ede595099732238bad3108f83e1a9524d65
- Region: South Central US

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ejizba** [comment]
Hi @bkhajuri please add more information, at least the repro steps and error you are getting
