### ISSUE TITLE
How do I use one of multiple User Assigned Identities with `output`s

### ISSUE THREAD

**Issue by smolattack** [Azure/azure-functions-nodejs-library#122]
@azure/functions  4.0.0-alpha.11
Node 18.16.1

```ts
import { app, output } from "@azure/functions";

const cosmosOutput = output.cosmosDB({
  connection: "COSMOS",
  containerName: "container",
  databaseName: "db",
});

app.storageQueue("testq", {
  queueName: "whatever",
  connection: "AzureWebJobsStorage",
  handler: async function (_, context) {
    context.extraOutputs.set(cosmosOutput, { test: "test" });
  },
  extraOutputs: [cosmosOutput],
});
```
The example code above errors even in a local dev environment with the following error message as soon as a queue item is processed:
```
Executed 'Functions.testq' (Failed, Id=a2b3d0f3-abf8-499d-adef-a92d55271460, Duration=7ms)
[2023-08-23T10:19:18.648Z] System.Private.CoreLib: Exception while executing function: Functions.testq. Microsoft.Azure.WebJobs.Extensions.CosmosDB: The CosmosDB connection string must be set either via the 'CosmosDB' IConfiguration connection string, via the CosmosDBAttribute.ConnectionStringSetting property or via CosmosDBOptions.ConnectionString.
```

I've been able to verify that `process.env.COSMOS` returns the correct connection string.

And as per the title, I would prefer to use a user assigned managed identity (this function app will have 2, where only one will have access to the CosmosDB resource). Looking at the `output#cosmosDB` types, I've been unable to figure out how to supply a managed identity. 

I'm already leaning towards using the cosmos client sdk but I'm curios if this can be done with output bindings

**Comment by ejizba** [comment]
Yes, this should be possible. First of all, make sure your extension bundle is up to date in your host.json (I believe `[4.*, 5.0.0)` is what you want). Your error message mentions "ConnectionStringSetting", which was the old naming.

Next, you would need the following local settings or app settings

- `COSMOS__accountEndpoint`
- `COSMOS__credential`
- `COSMOS__clientId` or `COSMOS__managedIdentityResourceId`

I wouldn't call myself an expert on managed identity, but I've gotten it to work a couple times. Here's the docs I found most helpful:

https://learn.microsoft.com/azure/azure-functions/functions-bindings-cosmosdb-v2-output?pivots=programming-language-javascript#identity-based-connections

**Comment by smolattack** [comment]
But what if I wanted to use an App Configuration instead of function app settings https://learn.microsoft.com/en-us/azure/azure-app-configuration/overview?

Also, the `connection` is a required property in CosmosDBv4OutputOptions. So if I was to use the suggested app settings, what would I supply to `connection`?

**Comment by ejizba** [comment]
I've never personally tried app configuration. I would have to look into it more, but the docs make it seem like it should work

The value should match the prefix you use in all the app settings. Since you used `connection: "COSMOS"`, that's why I made "COSMOS" the prefix in my example app settings. You should keep connection as-is.

**Comment by smolattack** [comment]
I see what you mean. Thanks for explaining but the use of magic strings and lack of referential transparency makes this a poor DX. I think I'll stick to using the Cosmos SDK for now
