### ISSUE TITLE
No functions found because of missing index.js file

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-library#124]
_Originally posted by @ivaaan in https://github.com/Azure/azure-functions-nodejs-library/issues/123#issuecomment-1692694564_

I'm experiencing the same issue, and it also started happening around 48h ago, and also with a function that used to work perfectly and caused no issues prior to.

Here are some logs: https://github.com/microsoft/vscode-azurefunctions/issues/3659#issuecomment-1689179569

I don't have a "main" field in `package.json` though, here's what I have:

```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "prestart": "npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\"",
    "prettier-format": "prettier --config .prettierrc 'src/**/*.ts' --write"
  },
  "dependencies": {
    "nodemon": "^3.0.1",
    "ts-node": "^10.9.1"
  },
  "devDependencies": {
    "@azure/functions": "^3.0.0",
    "@types/node": "^18.17.5",
    "@typescript-eslint/eslint-plugin": "^6.4.0",
    "@typescript-eslint/parser": "^6.4.0",
    "azure-functions-core-tools": "^4.x",
    "eslint": "^8.47.0",
    "typescript": "^4.9.5"
  }
}
```

My `function.json` points to: `"scriptFile": "../dist/HttpTrigger2/index.js"` and that's correct.

What else can I post that could help?

**Comment by ejizba** [comment]
Hi @ivaaan I'm seeing this error for your app:

> The 'HttpTrigger1' function is in error: Invalid script file name configuration. The 'scriptFile' property is set to a file that does not exist.

Can you double check that you deployed the dist directory? And that the path matches?

**Comment by ivaaan** [comment]
Yep, the path seems to match (and I haven't changed the folder structure after getting it to work last week). Please see the screenshot:

<img width="649" alt="Screenshot 2023-08-25 at 09 22 32" src="https://github.com/Azure/azure-functions-nodejs-library/assets/32945574/d5c8e9d8-04a0-4086-97a5-70d4b75c20d0">


How can I check whether `dist` folder has been deployed? I'm using this menu in the VSCode plugin:

<img width="569" alt="Screenshot 2023-08-25 at 09 24 34" src="https://github.com/Azure/azure-functions-nodejs-library/assets/32945574/59651838-68c0-4d69-960d-91d16db4fec6">

**Comment by ejizba** [comment]
Well normally I would say you can view the remote files in VS Code, but that's broken right now https://github.com/microsoft/vscode-azurefunctions/issues/3807

You could use the "scm" site to view the remote files, for example:

https://&lt;your app name&gt;.scm.azurewebsites.net/api/vfs/site/wwwroot/dist/HttpTrigger2/

(`site/wwwroot` is the root of your app code. You can adjust following parts of the url as desired to check different folders)

**Comment by ejizba** [comment]
Also I see the folder in your screenshot, but I don't see the index.js file. For the sake of sanity, can you double check you ran a build and that it succeeded in creating the file?

**Comment by ivaaan** [comment]
Yes, the `index.js` is there (in each respective folder):

<img width="324" alt="Screenshot 2023-08-25 at 11 08 57" src="https://github.com/Azure/azure-functions-nodejs-library/assets/32945574/e381a6d0-0731-45a1-900c-3d02fb2cd194">

But the "scm" site doesn't see `dist`:

```
{"Message":"'C:\\home\\site\\wwwroot\\dist\\HttpTrigger1\\' not found."}
```

All the other folders & files (except `dist`) are there. So the problem is that `dist` is not getting deployed.

**Comment by ejizba** [comment]
Hmm double check the `.funcignore` file to make sure you don't have `dist` listed there. Those files are ignored when deploying.

Are you by chance trying to use remote build when deploying? If you're not familiar with it, you probably aren't using it. Also what type of app is this? Windows/Linux, Consumption/Dedicated/Premium?

**Comment by ivaaan** [comment]
Aha! I don't have a `.funcignore` but I did have `dist` in my `.gitignore`. Removing this seemed to help! But I do need to ignore `dist` when delivering a GitHub repo to my client, how do I ignore it in Git but deploy to Azure?

**Comment by ejizba** [comment]
Have you changed your deployment method at all? Are you using local git deploy by chance? For a standard deployment method, the .gitignore should not be affecting your deployment files

**Comment by ivaaan** [comment]
Not at all! I've been using the UI of Azure Functions for Visual Studio Code the whole time.

**Comment by ejizba** [comment]
@ivaaan I think this is actually a bug on the VS Code extension. See https://github.com/microsoft/vscode-azurefunctions/issues/3817

Can you try adding a `.funcignore` file? I think VS Code will use that file instead of `.gitignore` as long as it exists. Here's a standard `.funcignore`:
```
*.js.map
*.ts
.git*
.vscode
__azurite_db*__.json
__blobstorage__
__queuestorage__
local.settings.json
test
tsconfig.json
```

**Comment by ejizba** [comment]
Closing as this was a bug on the VS Code extension. This was fixed by them and should hopefully be released soon. Follow the VS Code [issue](https://github.com/microsoft/vscode-azurefunctions/issues/3817) for more info.
