### ISSUE TITLE
No functions found because of connection string and export/import errors

### ISSUE THREAD

**Issue by dan-opitz** [Azure/azure-functions-nodejs-library#125]
I've successfully deployed a few v3 Node Functions using the Zip Deploy method and setting the `WEBSITE_RUN_FROM_PACKAGE` variable to a Blob Storage that the Function App has access to.

I tried creating a simple v4 Node Function in the same manner however it's not being loaded.  I see the following in the logs:

```
2023-08-25T14:42:02.476 [Information] Loading functions metadata
2023-08-25T14:42:02.479 [Information] Reading functions metadata
2023-08-25T14:42:02.479 [Information] 1 functions found
2023-08-25T14:42:02.479 [Information] 0 functions loaded
```

But I'm not seeing any other `WARNINGS` or `ERRORS` on why the function is not loading.

#### Investigative information

Please provide the following:

- Timestamp: 2023-08-25T14:42:02.476 
- Invocation ID: Unable to obtain as function is not loading
- Region: centralus

#### Repro steps

Create a v4 Function as follows:

```js
// /src/functions/event-reconciler.js

const { app } = require('@azure/functions');

export async function eventReconciler(messages, context) {
    context.log(`eventHubTriggerMany processed ${messages.length} messages`);
    for (const message of messages) {
        context.log(`eventHubTriggerMany was triggered by "${message}"`);
    }
}

app.eventHub('eventReconciler', {
    connection: process.env.CONNECTION_STRING,
    eventHubName: process.env.EVENT_HUB_NAME,
    cardinality: process.env.CARDINALITY,
    consumerGroup: process.env.CONSUMER_GROUP,
    handler: eventReconciler
});
```

```json
// package.json
{
    "name": "js-function",
    "version": "1.0.0",
    "description": "",
    "main": "src/functions/*.js",
    "scripts": {
        "start": "func start --verbose",
        "test": "echo \"No tests yet...\""
    },
    "dependencies": {
        "@azure/functions": "^4.0.0-alpha.11"
    }
}
```

```json
// host.json
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[4.0.0, 5.0.0)"
    }
}
```

`WEBSITE_RUN_FROM_PACKAGE` is set to the URL of the Zip File and this seems to be getting pulled successfully as it's finding the function but not loading it.

`AzureWebJobsFeatureFlags` is set to `"EnableWorkerIndexing"`

```
// Dir Structure of ZIP after unzipped

├── src/
│   └── functions/
│       └── event-reconciler.js
├── package.json
├── node_modules/
│   └── <ALL MODULES HERE>
└── host.json
```

#### Expected behavior

I would expect that if the function is found it is loaded and will be accessible via the Azure Portal.

#### Actual behavior

It seems that the function is found however isn't being loaded for some reason.  This means the function is not running and not accessible/listed in the Azure Portal.

#### Known workarounds

No known workarounds - looking for more troubleshooting steps to determine why the function is being found but not loaded.

#### Related information 

I'm not sure if I'm missing anything obvious here but been struggling with it for a bit now. Are there any other logs I can look into to get more insight?

`@azure/functions` Version: `^4.0.0-alpha.11`
Azure Function Version (based on Host Status Logs): `4.25.2.2`
Node Version (set in App Settings): `18`
extensionBundle Version (based on Host Status Logs): `4.8.0`

**Comment by ejizba** [comment]
```
app.eventHub('eventReconciler', {
    connection: process.env.CONNECTION_STRING,
    eventHubName: process.env.EVENT_HUB_NAME,
    cardinality: process.env.CARDINALITY,
    consumerGroup: process.env.CONSUMER_GROUP,
    handler: eventReconciler
});
```

^ My guess is that using `process.env` might be the problem. I've never seen someone doing that - it might work for most settings, but I don't think it'll work for `connection`. That's supposed to be the _name_ of the app setting ("CONNECTION_STRING" in your case?) not the _value_. You should check the `traces` table in your app insights for more logs on this

If you want me to take a look at our backend logs, you can either share the app name here or follow these instructions to share it privately. There's an option at the bottom for how to do it even if the app isn't running. https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by dan-opitz** [comment]
Ah good catch - yeah reading about the connection parameter [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cin-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-javascript#connection-string) it looks like I should just need to set it `CONNECTION_STRING`.

Also tried explicitly setting the other parameters without `process.env`:

```javascript
app.eventHub('eventReconciler', {
    connection: 'CONNECTION_STRING',
    eventHubName: 'application-logs',
    cardinality: 'many',
    consumerGroup: '$Default',
    handler: eventReconciler
});
```

It shouldn't matter if the `CONNECTION_STRING` App Setting is set as a KeyVault Reference, correct?  I do see it's able to resolve it.

But still seeing the same logs:

```bash
2023-08-25T18:08:04.512 [Information] Starting JobHost
2023-08-25T18:08:04.512 [Information] Starting Host (HostId=xxx, InstanceId=xxx, Version=4.25.2.2, ProcessId=24, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
2023-08-25T18:08:04.518 [Information] Loading functions metadata
2023-08-25T18:08:04.523 [Information] Reading functions metadata
2023-08-25T18:08:04.525 [Information] 1 functions found
2023-08-25T18:08:04.526 [Information] 0 functions loaded
2023-08-25T18:08:04.530 [Information] Generating 0 job function(s)
2023-08-25T18:08:04.535 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

Still seeing the same behavior with this change though and I had been combing through the `traces` last night but never saw anything that stuck out.

```bash
curl -v 'https://${FUNCTION_NAME}.scm.azurewebsites.net/api/7b749b17-4184-4faf-a610-08799fa12227' && date -u
```
Appreciate any other insight/ideas you have!  Thank you!

**Comment by ejizba** [comment]
I'm seeing the following errors at various points in time for your app:

> Worker was unable to load entry point 'src/functions/event-reconciler.js': Unexpected token 'export'

> Worker was unable to load entry point 'src/functions/ghec-event-reconciler.js': Cannot use import statement outside a module,

If you set `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` to `1`, you should be able to see these errors yourself in your app insights `traces` table

**Comment by dan-opitz** [comment]
That pointed me in the right direction - got it up and running now!

I did see that App Setting mentioned in a few other issues (specifically #123) recently.  What is best practice or the recommendation for this setting going forward - `0` or `1`?

Thank you @ejizba!

**Comment by ejizba** [comment]
I would strongly recommend `1`!

This is a breaking change in behavior and the app setting is only meant as a way to help with the transition. Starting in Node.js v20 (preview support coming soon!), all apps will use the `1` behavior and the app setting will do nothing.
