### ISSUE TITLE
No functions found because of duplicate function registered

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-library#126]
_Originally posted by @rrohm33 in https://github.com/Azure/azure-functions-nodejs-library/issues/123#issuecomment-1693928356_

@ejizba Am noticing a similar discrepancy. When deploying the same commit of a function app prior to rollout on v4.23 azurefunctions sdkVersion, resulted in 47 functions loaded. Then after rollout on v4.24.4 have only 31 functions loaded, and I don't see anything indicating a failure to load a file. Was just wondering if there is any way to manually specify using older version by setting linuxFxVersion or any other means, to get back up and running?

**Comment by ejizba** [comment]
@rrohm33 please share your app name or follow these instructions: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by rrohm33** [comment]
InvocationId: dfe0028f-d11b-4203-afaa-8f9ba70e8f92
Timestamp: 2023-08-23T21:26:41.5774037Z
Region: US-EAST

**Comment by ejizba** [comment]
Here's what I see:

> Worker was unable to load entry point 'dist/src/functions/products/index.js': A function with id 'getManufacturers' has already been registered.

This behavior changed in 4.24 (release notes [here](https://github.com/Azure/azure-functions-nodejs-worker/releases/tag/v3.7.0)) related to https://github.com/Azure/azure-functions-nodejs-library/issues/62

Ideally you would fix the error, but you can also catch & ignore the error in your own code if you want. It's not recommended to pin to an old host version, but yes that is possible. Instructions here: https://learn.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal#manual-version-updates-on-linux

**Comment by rrohm33** [comment]
Ahh thanks a ton! Don't know how I missed that.

**Comment by ejizba** [comment]
No problem, you can't see the error yet in Azure 😢 Once https://github.com/Azure/azure-functions-nodejs-library/issues/85 finishes rolling out with host 4.25 you will see the error in app insights `traces` table
