### ISSUE TITLE
Support service bus 'cardinality' setting for batches

### ISSUE THREAD

**Issue by smolattack** [Azure/azure-functions-nodejs-library#129]
#### Repro steps

Provide the steps required to reproduce the problem:
1. add batchOptions  host.json
```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  },
  "extensions": {
    "serviceBus": {
      "batchOptions": { "maxMessageCount": 50 },
      "messageHandlerOptions": {
        "maxConcurrentCalls": 4
      }
    }
  },
  "concurrency": {
    "dynamicConcurrencyEnabled": true,
    "snapshotPersistenceEnabled": true
  }
}

```

My expectation is that my function will now be passed an array of messages but that's not the case. The following code errors as ServiceBusQueueHandler only allows for a single message.

```ts
app.serviceBusQueue("sbq", {
  connection: "SERVICEBUS",
  queueName: "msgq",
  handler(
    messages: unknown[],
    context: InvocationContext
  ) {},
  isSessionsEnabled: true,
});
});
```
Also, at runtime, I see only a single message rather than an array

#### Expected behavior

When the maxMessageCount maxMessageCount is set, I would expect the function to try to batch messages if there are more than one in the queue.

* Programming language used typscript
* Links to source
* Bindings used serviceBusQueue

**Comment by ejizba** [comment]
I just tried it myself and apparently there's a "cardinality" setting which isn't documented that needs to be set to `many`.

As a temporary workaround, I think this would work:
```typescript
app.generic('serviceBusQueueTrigger2', {
    trigger: trigger.serviceBusQueue({
        connection: 'SERVICEBUS',
        queueName: 'msgq',
        // @ts-ignore
        cardinality: 'many',
    }),
    handler: serviceBusQueueTrigger2,
});
```
