### ISSUE TITLE
Creating an instance of EventEmitter leads to the azure function not beeing available

### ISSUE THREAD

**Issue by Robstei** [Azure/azure-functions-nodejs-library#138]
Creating an instance of EventEmitter leads to the azure function not beeing available.

#### Repro steps
 Create an azure function with

```javascript
const myEmitter = new EventEmitter()
```

#### Expected behavior

It should either:
1. Give an error
2. work

#### Actual behavior

The function won't be available. No error or warning provided.

#### Related information

I used version 4.0.0-alpha.12.

There is no information regarding Eeventemitters in the docs.

Not an expert and new to Azure, this behavior might be logical given the serverless nature of azure functions.

Hope this is the right place.

**Comment by ejizba** [comment]
@Robstei Are you running this locally or in Azure? You should see at least a warning if you're running locally. Creating an EventEmitter should be fine - how are you importing it, though? That might be the problem.

**Comment by Robstei** [comment]
You are right.

The error came from importing EventEmitter from "stream" instead of "events".

Sry for taking your time.

**Comment by ejizba** [comment]
No problem, glad you got it figured out!
