### ISSUE TITLE
Service bus 'cardinality' causes messages to go missing

### ISSUE THREAD

**Issue by smolattack** [Azure/azure-functions-nodejs-library#141]
I've tried using the cardinality set to "many" in version 4.0.0-alpha.12.20230912.4. As you can see from the screenshot, service bus is sending out a lot more messages than are coming in. The function app was run locally as I can't deploy it to the cloud. Near the end of the graph in the screenshot, I removed the cardinality setting and I got down to around 500 messages. Ignore the dip as that's when I switched off the function and curled up in bed to have a little cry (j/k, did cry on the inside though).

![cardinality](https://github.com/Azure/azure-functions-nodejs-library/assets/74571687/37fa81e3-ccaf-4e65-8509-5d6323831477)

Here, you can see the difference with cardinality off, and no other changes to the code other than one line of code to handle single messages:
```ts
  const messagesArray = Array.isArray(messages) ? messages : [messages];
```
![nocardinality](https://github.com/Azure/azure-functions-nodejs-library/assets/74571687/dc9ec02c-dbec-4414-b4c4-540282cb5a7a)

So although 4 million messages were "sent out" , the amount of messages dequeued was very few (less than 10k the entire night).

I could confirm by live debugging locally that my function was called at a very slow rate. So even though the messages came in batches, I was processing very few messages overall. I don't know where those 4 million messages have gone (my function only saw/processed less than 10k). 

This queue had sessions enabled and all incoming messages had the same session ID as the triggered function's job is to patch cosmos db items (without sessions, I'd be getting duplicates and conflicts/collisions).

**Comment by ejizba** [comment]
I can try to repro myself when I find time, but this starts to get outside the wheelhouse of the Node.js world. We pass along your settings (like cardinality), but the actual service bus stuff is handled by a [service bus extension](https://github.com/Azure/azure-functions-servicebus-extension) shared across all languages.

This could be related to your service bus settings in host.json, your settings on the service bus resource itself, or even your telemetry/metric settings. Could be hard to narrow it down, but again I doubt it would be something Node.js-specific

**Comment by ejizba** [comment]
As mentioned I don't think this is a Node.js problem, so I'm going to go ahead and close. If you still need help, the fastest option is to file a support case as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-troubleshoot?pivots=nodejs-model-v4#get-help-from-microsoft). If you don't have a support plan or want to use GitHub I'd file an issue on the service bus extension. It's one of these repos, I'm not exactly sure:
- https://github.com/Azure/azure-functions-servicebus-extension
- https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus
