### ISSUE TITLE
Event Grid Trigger on new programming model

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-nodejs-library#15]
On new programming model, `EventGridTrigger` cannot be seen at `app` root object.
![image](https://user-images.githubusercontent.com/4566555/188555549-f774b199-cb51-48da-8fdd-507997ccd6f6.png)

Do we have a plan to add the trigger? Or is there a workaround?

**Comment by ejizba** [comment]
@horihiro the workaround is to use the `app.generic` method which can be used for any trigger type

Plan is to add triggers based on usage & feedback, so yes we can add event grid since you asked for it :)

**Comment by horihiro** [comment]
Thanks @ejizba ,
Do we have examples for `app.generic` or a plan to publish it?

**Comment by ejizba** [comment]
Not yet but we should. I'll track that here: https://github.com/Azure/azure-functions-nodejs-library/issues/19

**Comment by horihiro** [comment]
Thanks!

**Comment by ejizba** [comment]
Fixed in https://github.com/Azure/azure-functions-nodejs-library/pull/20
