### ISSUE TITLE
Wrong order of arguments in release of 4.0.0

### ISSUE THREAD

**Issue by Andersos** [Azure/azure-functions-nodejs-library#154]
I was reading the releases log for 4.0.0 and could not help to notice that I think there might have been a mistake in https://github.com/Azure/azure-functions-nodejs-library/releases/tag/v4.0.0 third bullet under Changed where it says: 
"Switch the order of arguments. For example, (request, context) is now (context, request) https://github.com/Azure/azure-functions-nodejs-library/issues/34"

Should it not say that it now is `(request, context)` not `(context, request)`. I dont think I can send a pull request to the release log though that is why I created this issue so it can be corrected if there is a mixup.

<img width="892" alt="Screenshot 2023-09-28 at 19 52 10" src="https://github.com/Azure/azure-functions-nodejs-library/assets/288977/61cb3591-b965-4705-a4e9-7c74343eeb92">

**Comment by ejizba** [comment]
You are correct - fixed it, thanks!
