### ISSUE TITLE
Hot Reload not working - Model v4 - Typescript

### ISSUE THREAD

**Issue by rafaelgrilli92** [Azure/azure-functions-nodejs-library#165]
The hot reload doesn't seem to be working for me. I make changes on a file inside the "functions" folder and nothing happens. It seems like it's not watching for changes. The project and folder structure were automatically created using the Azure Tools for VS Code and it's a very simple project.

**Typescript 5.2.2
Core Tools Version: 4.0.5390
Function Runtime Version: 4.25.3.21264**

**Package.json**
`
{
"name": "americold-integration-api",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "clean": "rimraf dist",
    "prestart": "npm run clean && npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/functions": "4.0.1",
    "applicationinsights": "2.8.0",
    "moment": "2.29.4",
    "mongoose": "7.5.3"
  },
  "devDependencies": {
    "@types/node": "18.x",
    "rimraf": "5.0.0",
    "typescript": "5.2.2"
  },
  "main": "dist/src/functions/*.js"
}
`

**Comment by ejizba** [comment]
Are you using TypeScript watch by chance? It's the JavaScript files that actually get run, so making a change in `src/functions` won't help unless you're running `tsc -w` or `npm run watch` in addition to `func start`

If that doesn't help, please copy the logs of `func start` here

**Comment by ejizba** [comment]
Oh also double-check you have "extensionBundle" listed in your host.json file. I'm pretty sure VS Code adds this by default so it's probably not your problem, but we recently found a bug where it doesn't work if you don't have an extension bundle. See [the issue](https://github.com/Azure/azure-functions-host/issues/9586) for more details.

**Comment by rafaelgrilli92** [comment]
@ejizba thanks for the quick response! 

My host.json does have the extensionBundle:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.15.0, 4.0.0)"
  }
}
```

I wasn't actually running the "tsc -w" in addition to the func start, but even running both at the same time, the hot reload doesn't work. When I save the file, the terminal where the "watch" is running flickers for a second, but the changes are not made in the function. Also, I didn't know that I needed to run both at the same time. I didn't see anywhere saying that I needed that for the hot reload to work. Maybe I didn't research enough, but I spent quite some time looking for this with no success. So maybe it's something that needs to be more clear and easy to find in the documentation.

Here's the func start log from the terminal. If there are other logs that you need, where can I find them?
```
[2023-10-05T00:54:27.079Z] Worker process started and initialized.
Functions:
        createOrder: [POST] http://localhost:7071/api/order

For detailed output, run func with --verbose flag.
[2023-10-05T00:54:32.112Z] Host lock lease acquired by instance ID '0000000000000000000000004B52C1DB'.
```
Thank you!

**Comment by rafaelgrilli92** [comment]
Also, even if I make changes in the .js file inside the "dist/functions" folder, it doesn't seem to get the change. Should it hot reload if I manually change the .js file in the "dist" folder?

**Comment by ejizba** [comment]
Yeah updating the .js file inside the dist/functions folder should work.

Running "tsc -w" (or "npm run watch") is mostly just TypeScript tribal knowledge. It's nothing specific to Azure Functions, but I understand where you're coming from. Let us know where you would expect to find this documented and we can look at adding it

Here's what I see in my logs. You should see the bottom logs duplicated each time you save a file, which is what I was looking for. Make sure "func start" and "tsc -w" are both being run from the same root folder of your app
```
Azure Functions Core Tools
Core Tools Version:       4.0.5382 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.25.3.21264

[2023-10-05T01:20:31.759Z] Worker process started and initialized.

Functions:

        httpTrigger1: [GET,POST] http://localhost:7071/api/httpTrigger1

For detailed output, run func with --verbose flag.
[2023-10-05T01:20:37.514Z] Host lock lease acquired by instance ID '000000000000000000000000017BE3A8'.
[2023-10-05T01:20:39.670Z] Worker process started and initialized.
[2023-10-05T01:20:44.940Z] Host lock lease acquired by instance ID '000000000000000000000000017BE3A8'.
[2023-10-05T01:20:49.194Z] Worker process started and initialized.
[2023-10-05T01:20:54.467Z] Host lock lease acquired by instance ID '000000000000000000000000017BE3A8'.
```

**Comment by rafaelgrilli92** [comment]
I found the issue... I had WEBSITE_RUN_FROM_PACKAGE=1 in my local.settngs.json. By removing it the hot reload works. I just needed to run "npm start" and "npm run watch" simultaneously. Thank you for your help!
