### ISSUE TITLE
Support Node 20

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-library#170]
Initial release: 2023-04-18
Active LTS start: 2023-10-24
https://github.com/nodejs/release#release-schedule

We [announced public preview](https://twitter.com/AzureFunctions/status/1702404087889662097) in September 2023 🎉

Please see our roadmap for the latest estimates on the GA timeline: https://github.com/Azure/azure-functions-nodejs-library/wiki/Roadmap

**Comment by nathanchase** [comment]
In the portal (https://portal.azure.com/), I have no way of choosing Node 20 in my Web App's configuration.
![image](https://github.com/Azure/azure-functions-nodejs-library/assets/5963574/64b94452-396e-484a-90db-b69c0dcf45bd)
What is the timeframe for the portal to be updated to support Node 20 for [Web Apps](https://azure.microsoft.com/en-us/products/app-service/web)?

**Comment by ejizba** [comment]
Hi @nathanchase this repo and my team only focuses on function apps. Unfortunately I don't know when the Web Apps team will update that

**Comment by nathanchase** [comment]
> Hi @nathanchase this repo and my team only focuses on function apps. Unfortunately I don't know when the Web Apps team will update that

Thanks for the reply. Is there a public repo or any other method of feedback with the Web Apps team that you're aware of?

**Comment by ejizba** [comment]
I pinged some folks offline, but I'm not getting much of a response. Unfortunately I don't think they have any public place for feedback. Last year web apps announced Node 18 on [Nov 30th](https://azure.microsoft.com/en-us/updates/generally-available-new-versions-supported-for-languages-and-frameworks-in-azure-app-service/), so that's probably the best indicator of approximately when it might happen this year as well

**Comment by ejizba** [comment]
https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-for-nodejs-20/
