### ISSUE TITLE
Wait to start consuming requests

### ISSUE THREAD

**Issue by charlesgardyn** [Azure/azure-functions-nodejs-library#174]
Is there a way to make the function do some execution before start receiving requests, like connecting to a database?

**Comment by ejizba** [comment]
Hi @charlesgardyn what plan are you using? Consumption? Premium? A [warmup trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=isolated-process&pivots=programming-language-javascript) might work, although it's not supported on all plans. I've filed this issue to track that work: https://github.com/Azure/azure-functions-nodejs-library/issues/176

If you're on consumption (like most people), we'd have to come up with an alternative. You can definitely run code at app startup in various ways, but requests might be starting to queue up, so not sure how much that helps.

**Comment by charlesgardyn** [comment]
I'm using Premium

**Comment by castrodd** [comment]
@charlesgardyn Warmup triggers are supported on Premium. Have you been able to try them for your use case? Let us know if that addresses your needs and I will close this issue once we hear back from you.

**Comment by charlesgardyn** [comment]
It does, thank you!
