### ISSUE TITLE
EventGridOutput doesn't contain all types for typescript

### ISSUE THREAD

**Issue by kubop** [Azure/azure-functions-nodejs-library#177]
One way to define connection to an Event Grid is to use identity based connection, see [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-output?pivots=programming-language-javascript&tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv3#identity-based-authentication). However, when dealing with Typescript, the connection property doesn't seem to exist:

`Argument of type '{ connection: string; }' is not assignable to parameter of type 'EventGridOutputOptions'.`

Sample code:
```ts
const eventGridOutput = output.eventGrid({    
    connection: 'EmailServiceTopic'
})
```

#### Repro steps

1. Create a .ts function
2. Install the latest `@azure/functions`
3. Define return function output:
```ts
import { app, output } from '@azure/functions';

const eventGridOutput = output.eventGrid({    
    connection: 'EmailServiceTopic'
})

app.serviceBusQueue('ACSEmailMessageQueueTrigger', {
    connection: 'ServiceBusEmailQueue',
    queueName: 'emailservice-queue',
    return: eventGridOutput,
    handler: ....
})
```

#### Expected behavior

EventGridOutputOptions type should contain `connection` property.

#### Actual behavior

`Argument of type '{ connection: string; }' is not assignable to parameter of type 'EventGridOutputOptions'.`

#### Known workarounds

Use Javascript instead of Typescript or suppress TS warnings.

#### Related information 

NodeJS version 18.x
@azure/functions 4.0.1

**Comment by ejizba** [comment]
Hi @kubop thanks for the report! In addition to the workarounds you listed, you could use `output.generic` as discussed [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Clinux%2Cazure-cli&pivots=nodejs-model-v4#generic-inputs-and-outputs)
