### ISSUE TITLE
HttpTriggerOptions default AuthLevel is inconsistent with Functions documentation

### ISSUE THREAD

**Issue by RaduG** [Azure/azure-functions-nodejs-library#189]
https://github.com/Azure/azure-functions-nodejs-library/blob/8edd622e9564e56bd71031642624200295ccd1da/types/http.d.ts#L31C1-L36C1

The [Azure Functions documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-typescript#http-auth) states that the `function` authLevel is the default one if not set. However, the when using the library, the default is `anonymous`.

Unless there is a good reason that I completely missed, for avoidance of doubt the library should be aligned to the generic documentation.

**Comment by ejizba** [comment]
Hi @RaduG it would be a breaking change to adjust the default in the library at this point, but we can easily update the docs for Node.js
