### ISSUE TITLE
1 Function app - 2 different auths?

### ISSUE THREAD

**Issue by diberry** [Azure/azure-functions-nodejs-library#197]
Can I have 1 Function app with 2 different auths - related to #196

Front end should only call API with auth user. 
Secondary process can call API without auth?

**Comment by castrodd** [comment]
Hey @diberry! I looked into this for you and it seems to me like this is not possible.

If we are talking about the built-in authentication feature in Azure, then authentication is applied to the entire function app, not individual functions.

As far as I can see, there is no way to configure the built-in authentication to apply only to certain functions and not others.

Now, if you were to hand-roll your own authentication, then you could conceivably have different authentication schemes for each function. However, this is strongly discouraged. As the [docs here](https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#identity-providers) put it, "You're not required to use this feature for authentication and authorization. You can use the bundled security features in your web framework of choice, or you can write your own utilities. However, you will need to ensure that your solution stays up to date with the latest security, protocol, and browser updates."
