### ISSUE TITLE
Dependencies not logged

### ISSUE THREAD

**Issue by sga-solita** [Azure/azure-functions-nodejs-library#217]
The documentation says that if I register application insights at the start of the application, then dependency calls should be tracked automatically (https://learn.microsoft.com/en-us/azure/azure-functions/functions-monitoring#dependencies). That is not the case, as we have no http-requests logged in dependencies, only database and storage calls.

Also, I couldn't find how to track dependencies manually, using InvocationContext, which would make it possible to track imap/smtp etc.

#### Investigative information

N/A as sample code is provided

#### Repro steps

Run a simple function (v4) with a fetch request:
```
import { app, HttpRequest, HttpResponseInit, InvocationContext } from "@azure/functions";

export async function sendHttpRequest(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`);

    // Send request to the url
    const response = await fetch("https://www.example.com");
    const body = await response.text();

    context.log(`Http function processed request for url "https://www.example.com" with status code "${response.status}" and response body "${body}"`);

    return {
        status: response.status,
        body: body
    };
};

app.http('sendHttpRequest', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: sendHttpRequest
});

```

#### Expected behavior

Dependency call to https://www.example.com logged in application insights.

#### Actual behavior

No dependency logged.

#### Known workarounds

If there was a custom way to track dependencies, it could be used, but I haven't found it for Azure Functions, using the builtin context logging.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ejizba** [comment]
Hi @sga-solita, the auto-tracking doesn't apply to all languages - I believe those docs are specific to .NET. Regardless, it should be relatively simple to set up dependency tracking. You need to use the [applicationinsights](https://www.npmjs.com/package/applicationinsights) npm package. Unfortunately they don't support native fetch yet (see [this issue](https://github.com/microsoft/ApplicationInsights-node.js/issues/1104)), but you could workaround it by using the [node-fetch](https://www.npmjs.com/package/node-fetch) npm package. Here's some sample code using v2 of applicationinsights and v2 of node-fetch


```typescript
import { app, HttpRequest, HttpResponseInit, InvocationContext } from "@azure/functions";
import * as appInsights from 'applicationinsights';
import { default as fetch } from 'node-fetch';

// NOTE: You only need to do this from one file in your app, not all files
appInsights.setup().start();

export async function sendHttpRequest(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`);

    // Send request to the url
    const response = await fetch("https://www.example.com");
    const body = await response.text();

    context.log(`Http function processed request for url "https://www.example.com" with status code "${response.status}" and response body "${body}"`);

    return {
        status: response.status,
        body: body
    };
};

app.http('sendHttpRequest', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: sendHttpRequest
});
```

**Comment by sga-solita** [comment]
Thank you for the information, I might have misunderstood the docs. I will look into your sample code 😊
