### ISSUE TITLE
ApplicationInsights Custom Properties

### ISSUE THREAD

**Issue by cheng93** [Azure/azure-functions-nodejs-library#227]
#### Investigative information

How would you add properties to ApplicationInsights' Custom Properties 

#### Repro steps

https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=typescript%2Clinux%2Cazure-cli&pivots=nodejs-model-v4#logging

```ts
context.log(`Something has happened. Invocation ID: "${context.invocationId}"`, { foo: 1, bar: 2 });
```

#### Expected behavior

It shows up in CustomProperties

![image](https://github.com/Azure/azure-functions-nodejs-library/assets/13205912/7d909436-0aaf-4069-be8c-7bb13f57ccb0)

#### Actual behavior

context.log can take several arguments, however all this does is concate them into one string and it ends up in the `TraceProperties.Message`

**Comment by ejizba** [comment]
Unfortunately I don't think it's possible to add custom properties through `context.log`. You'd have to use the application insights npm package directly instead of using context.log: https://www.npmjs.com/package/applicationinsights

**Comment by cheng93** [comment]
Thanks, that's where I headed down while waiting for a response
