### ISSUE TITLE
Use hooks for third party logging

### ISSUE THREAD

**Issue by cheng93** [Azure/azure-functions-nodejs-library#228]
#### Investigative information

We would like to hook a third party logging library (pino, winston) in context.log, so that we can send it to another sink, that isn't application insights (in our case it's seq).

Is it possible to hook this in?

In .NET we can use `ILogger` / `ILoggerFactory`, but I'm unsure how to do this with node

**Comment by ejizba** [comment]
Hooks are probably your best bet: https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4#hooks

I think something like this would work if you want to completely replace app insights:
```typescript
app.hook.preInvocation((context) => {
    context.invocationContext.log = (...args) => {
        // your logic here
    };
});
```

If you want your seq stuff and app insights at the same time, it gets a little more clunky, but I think this would work:
```typescript
app.hook.preInvocation((context) => {
    const newContext = {
        ...context.invocationContext,
        log: (...args) => {
            // your logic here

            context.invocationContext.log(...args);
        },
    };
    context.inputs.push(newContext);
});
```

Hooks are relatively new, so if there's anything missing please file a feature request

**Comment by ejizba** [comment]
I feel like this might be a common scenario, so I'll count this as its own feature request to come up with a "recommended" design for people and make sure its nice and easy

**Comment by ejizba** [comment]
Just merged a PR that will be the new recommended way to do this. It relies on some changes in Azure which will take a month or two to roll out, so I'll update here once that finishes.

Here's what the new feature will look like:
```typescript
const customLogger = new CustomLogger();

app.hook.log((logContext) => {
    customLogger.emit({
        body: logContext.message,
        severity: logContext.level,
    });
});
```

**Comment by ejizba** [comment]
Fyi this is ready to be used. You need Host v4.34+ which should be done rolling out in Azure or core tools v4.0.5801 if running locally which was just released today. Oh and v4.5.0 of this package which we also just released today
