### ISSUE TITLE
Multiple Routes for one function (Azure Function App Node v4)

### ISSUE THREAD

**Issue by ihnaqi** [Azure/azure-functions-nodejs-library#239]
I need an azure function which would incorporate multiple flavours of a request. Here is what I am expecting it to do.

#### Nature of hits
So this function app will get hit by the following type of requests

- hit/?tag=something
- hit/something

```javascript
app.http('hit', {
   authLevel: 'anonymous',
   methods: ["POST"],
   handler: async (request, context) {
       // Handler code goes here
   }
})
```

#### Known Workarounds and Problem 

I know that Azure provides `route` parameter in the __HttpTriggerOptions__ which expects value of type string, and in order to be able to achieve the first type of request in my case I have to add the following line in the __HttpTriggerOptions__

-  `route: {tag}`

and for the second type of calls the options will look something like this:
- `route: 'something'`

but the problem is in order to be able to achieve both I would need two different function as of my knowledge, and that doesn't supports my business need. I have to handle both flavour of __API__ calls under one function. Is there any way to deal with it?
and also I cannot reproduce an __Azure function__ under the same name because that is not allowed something like the fllowing:

> **Warning:**
>
> Do not copy the following code, this is just for clarification of the above description.
```javascript 
app.http('hit', {
   route: '{tag}',
   authLevel: 'anonymous',
   methods: ["POST"],
   handler: async (request, context) {
       // this is is just and example and won't work with the below function already existing 
   }
})

app.http('hit', {
   route: 'something',
   authLevel: 'anonymous',
   methods: ["POST"],
   handler: async (request, context) {
       // this is is just and example and won't work with the above function already existing 
   }
})
```

**Comment by ejizba** [comment]
Hi @ihnaqi I saw you also commented on this issue: https://github.com/Azure/azure-functions-nodejs-library/issues/98. Can you explain a bit how this issue is different? Or can we close this as a duplicate?

> but the problem is in order to be able to achieve both I would need two different function as of my knowledge, and that doesn't supports my business need. I have to handle both flavour of API calls under one function. Is there any way to deal with it?

If this is the only problem, you can always define the handler separately and just register it twice. Something like this:
```javascript
async function helloWorld(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`);

    const name = request.query.get('name') || (await request.text()) || 'world';

    return { body: `Hello, ${name}!` };
}

app.http('helloWorld', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: helloWorld,
});

app.http('helloWorld2', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: helloWorld,
});
```
