### ISSUE TITLE
High memory usage when posting a ~77mb payload to a HTTP trigger.

### ISSUE THREAD

**Issue by kevinvdburgt** [Azure/azure-functions-nodejs-library#241]
When posting a large payload (around 77mb of data) to a http trigger, node will use around 988mb on my machine.

As we have set limits on our k8s pods, the pods will be shutdown because it has ran out of memory. A workaround is that we increased the limits of the pods.

```http
POST http://localhost:7071/api/script HTTP/1.1
content-type: application/json

{"payload": ["77mb of data"]}
```

results in:

```
[2024-03-26T07:41:55.911Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.011Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.112Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.211Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.311Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.411Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.511Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.611Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.711Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.811Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
[2024-03-26T07:41:56.911Z] Rss: 988mb (lowest: 61mb, highest: 988mb)
```

---

Reproduction repository: https://github.com/vanwijnengroep/issue-azure-function-memory-usage

|package|version|
|---|---|
|azure-functions-core-tools|4.0.5611|
|node|18.16.1|
|os|Linux vw-kevin 6.1.0-18-cloud-amd64 Azure/azure-functions-core-tools#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux|

**Comment by ejizba** [comment]
Hi @kevinvdburgt, my first recommendation is to use http streams. It's still in preview, but this will by far make the biggest difference for large payloads. More info here: https://aka.ms/AzFuncNodeHttpStreams

Secondly, I'm not sure why it's using 988mb. Just to confirm, you're only sending one request at a time? And you're running locally? Are you using k8s when running locally or not?

**Comment by kevinvdburgt** [comment]
Hey @ejizba, we're still using the version 3 of the Node.js programming model (which is not supported).


> Secondly, I'm not sure why it's using 988mb. Just to confirm, you're only sending one request at a time? And you're running locally? Are you using k8s when running locally or not?

That is correct, after starting `npm run start` I've only sent a single request. Just running plain node on my machine without the use of k8s locally.

**Comment by ejizba** [comment]
In that case, I would first recommend upgrading to model v4. When I did that to your sample app, I'm already seeing improvements with ~300mb instead of ~900mb. We cleaned up quite a bit of our internal logic in the new model, so that's where I'm guessing the improvements are coming from. For example, it used to store the body as both a buffer and a string, which was obviously inefficient.

If you're not familiar with v4, here's how I upgraded your sample app. First, I deleted `./script/function.json`. Then I updated these two files:

package.json:
```json
{
  "scripts": {
    "prepare": "node examples/create-payloads.js",
    "start": "func start"
  },
  "dependencies": {
    "azure-functions-core-tools": "^4.0.5611",
    "@azure/functions": "^4.0.0"
  },
  "main": "./script/script.js"
}
```

script.js:
```javascript
const { app } = require('@azure/functions');

const usage = { lowest: null, highest: null };

const bytesToMegabytes = (bytes) => `${Math.round(bytes / 1024 / 1024)}mb`;

const reportUsage = () => {
  const memory = process.memoryUsage();

  if (usage.lowest === null || usage.lowest > memory.rss) {
    usage.lowest = memory.rss;
  }

  if (usage.highest === null || usage.highest < memory.rss) {
    usage.highest = memory.rss;
  }

  console.log(`Rss: ${bytesToMegabytes(memory.rss)} (lowest: ${bytesToMegabytes(usage.lowest)}, highest: ${bytesToMegabytes(usage.highest)})`)
}

setInterval(reportUsage, 100);

app.http('script', {
  methods: ['GET', 'POST'],
  handler: async (request, context) => {
    return {
      body: 'Hello, world!'
    }
  }
});
```

**Comment by ejizba** [comment]
Closing as this has already been improved with v4 model and also stream feature
