### ISSUE TITLE
Debugging in VS code terminates when hot reload is running `npm run watch`

### ISSUE THREAD

**Issue by exhaler** [Azure/azure-functions-nodejs-library#246]
#### Repro steps

Provide the steps required to reproduce the problem:

Github repo: https://github.com/exhaler/DebugSample
1. Create a function app in VS Code
2. Press `F5` to run debug mode
3. Open another terminal and run `npm run watch`
4. Azure functions will stop working with error: 

> The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command func host start" terminated with exit code: 1.
> Terminal will be reused by tasks, press any key to close it.

#### Expected behavior

Since i'm running `npm run watch` I expect the new changes to be applied and to continue debugging the function.

#### Actual behavior

`npm run watch` is running correctly detecting changes, however VS code debug terminal terminates.

#### Known workarounds

Running debug without `npm run watch` works, however when I save some changes on a `.ts` file, I have stop and re-launch the debugger again.

#### Related information 

* **Note**: Running `npm run watch` in a terminal and `func start` in another terminal works correctly and the changes are applied. This issue only happens when trying to debug the function in VS code `F5`
* Programming language
```
Windows 10
Azure Functions Core Tools
Core Tools Version:       4.0.5611 Commit hash: N/A +591b8aec842e333a87ea9e23ba390bb5effe0655 (64-bit)
Function Runtime Version: 4.31.1.22191
Node v18.20.2
typescript v4
```
<details>
<summary>launch.json</summary>

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Node Functions",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "preLaunchTask": "func: host start"
        }
    ]
}
```
</details>
<details>
<summary>tasks.json</summary>

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"label": "func: host start",
			"command": "host start",
			"problemMatcher": "$func-node-watch",
			"isBackground": true,
			"dependsOn": "npm build (functions)",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"type": "shell",
			"label": "npm build (functions)",
			"command": "npm run build",
			"dependsOn": "npm clean (functions)",
			"problemMatcher": "$tsc",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"type": "shell",
			"label": "npm install (functions)",
			"command": "npm install",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"type": "shell",
			"label": "npm prune (functions)",
			"command": "npm prune --production",
			"dependsOn": "npm build (functions)",
			"problemMatcher": [],
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"type": "shell",
			"label": "npm clean (functions)",
			"command": "npm run clean",
			"dependsOn": "npm install (functions)",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		}
	]
}
```
</details>
<details>
<summary>local.settings.json</summary>

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
  }
}
```
</details>
<details>
<summary>package.json</summary>

```json
{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "clean": "rimraf dist",
    "prestart": "npm run clean && npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/functions": "^4.0.0",
    "azure-ad-verify-token": "^3.0.3"
  },
  "devDependencies": {
    "@types/node": "^18.x",
    "rimraf": "^5.0.0",
    "typescript": "^4.0.0"
  },
  "main": "dist/src/functions/*.js"
}
```
</details>
<details>
<summary>host.json</summary>

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
```
</details>

**Comment by ejizba** [comment]
@exhaler I believe you need the "restart" flag in your launch.json to get this behavior. Full launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Node Functions",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "preLaunchTask": "func: host start",
            "restart": true
        }
    ]
}
```

**Comment by exhaler** [comment]
> @exhaler I believe you need the "restart" flag in your launch.json to get this behavior. Full launch.json:
> 
> ```json
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Attach to Node Functions",
>             "type": "node",
>             "request": "attach",
>             "port": 9229,
>             "preLaunchTask": "func: host start",
>             "restart": true
>         }
>     ]
> }
> ```

That did the trick, thanks! Is there a way to run `npm run watch` when the debugger starts instead of doing it manually each time in another terminal?

**Comment by ejizba** [comment]
Yeah do the following in your tasks.json file:
1. Add a watch task configuration
2. Update the "dependsOn" property of the "func: host start" task to point to the new watch task instead of the build task

```jsonc
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "label": "func: host start",
            "command": "host start",
            "problemMatcher": "$func-node-watch",
            "isBackground": true,
            "dependsOn": "npm watch (functions)"
        },
        {
            "type": "shell",
            "label": "npm watch (functions)",
            "command": "npm run watch",
            "dependsOn": "npm clean (functions)",
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        },
        // rest of your tasks
```

**Comment by exhaler** [comment]
> Yeah do the following in your tasks.json file:
> 
> 1. Add a watch task configuration
> 2. Update the "dependsOn" property of the "func: host start" task to point to the new watch task instead of the build task
> 
> ```js
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "type": "func",
>             "label": "func: host start",
>             "command": "host start",
>             "problemMatcher": "$func-node-watch",
>             "isBackground": true,
>             "dependsOn": "npm watch (functions)"
>         },
>         {
>             "type": "shell",
>             "label": "npm watch (functions)",
>             "command": "npm run watch",
>             "dependsOn": "npm clean (functions)",
>             "isBackground": true,
>             "problemMatcher": "$tsc-watch"
>         },
>         // rest of your tasks
> ```

That did the trick!
