### ISSUE TITLE
Table trigger with {id} isn't working

### ISSUE THREAD

**Issue by diberry** [Azure/azure-functions-nodejs-library#249]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

Example: 

1. Set up Storage table

<img width="931" alt="image" src="https://github.com/Azure/azure-functions-nodejs-library/assets/41597107/0895aeb5-00c1-4c7f-a127-5f7fcedc089b">

2. Set up and run v4 function code

```
const { app, input } = require('@azure/functions');

const tableInput = input.table({
    partitionKey: 'car',
    tableName: 'product',
   rowKey: '{id}',
   connection: 'AzureWebJobsStorage',
});

app.http('httpAndTable', {
    methods: ['GET'],
    connection: 'AzureWebJobsStorage',
    route: "products/{id}",
    extraInputs: [tableInput],
    handler: (request, context) => {

        try {

            context.log(`id: ${request.params.id}`); 

            const product = context.extraInputs.get(tableInput);
            context.log(`Product: ${JSON.stringify(product)}`);

            if (product) {
                return {
                    status: 200,
                    jsonBody:product
                };
            } else {
                return {
                    status: 400,
                    body: `There is no data for ID: ${id}`
                };
            }
        } catch (err) {
            context.log(`Error: ${err}`);
            return {
                status: 500,
                body: 'Internal Server Error'
            }
        }
    }
});
```

3. Notice that table binding, route, and context.log all use {id}. The URL is `/api/products/891bab72-7ac0-4680-82ca-cd07e317bd5c`, and the context.log displays that id. The function returns all rows instead of 1.

<img width="923" alt="image" src="https://github.com/Azure/azure-functions-nodejs-library/assets/41597107/09a49041-4009-4b30-842c-1040b0668e8b">

4. If the route returns the id correctly in the context.log, why isn't the table binding reducing the results to that row? 

<img width="650" alt="image" src="https://github.com/Azure/azure-functions-nodejs-library/assets/41597107/434b965b-1089-45d8-8e3b-5117755b2fb3">

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ejizba** [comment]
Looks like this is a known issue: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/848

I would recommend this as a workaround:

> filter: "RowKey eq '{rowKey}'"

Closing in favor of linked issue, especially as this is not unique to Node.js
