### ISSUE TITLE
Bearer authorization token is being trucanted.

### ISSUE THREAD

**Issue by exhaler** [Azure/azure-functions-nodejs-library#251]
#### Repro steps

Provide the steps required to reproduce the problem:

Github repo: https://github.com/exhaler/DebugSample
1. Create a function app in VS Code
2. Log this `request.headers.get("authorization");`
4. Push the changes to the static web app and wait until it deploys.
5. Check the logs to see that authorization is truncated to 365 chars.
6. This only happens live and never while locally testing.

#### Expected behavior

To get the full authorization string being sent `Bearer eyJhbGciOiJSUzI1NiIsImtpZ....`

#### Actual behavior

Authorization header is being truncated to 365 characters, full sample:
> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MTQwMDExNjgsImV4cCI6MTcxNDAwMTQ2OCwiaWF0IjoxNzE0MDAxMTY4LCJpc3MiOiJodHRwczovLzI5NjUwNWM5LTU1OTMtNDE0MC1iNDNkLWE0NmQyMWUyMjNiZS5zY20uYXp1cmV3ZWJzaXRlcy5uZXQiLCJhdWQiOiJodHRwczovLzI5NjUwNWM5LTU1OTMtNDE0MC1iNDNkLWE0NmQyMWUyMjNiZS5henVyZXdlYnNpdGVzLm5ldC9henVyZWZ1bmN0aW9ucyJ9.PudR8AmjfUDRspT_x1_yCWS8e22l1PJ3mEIgYUOIuBY

#### Known workarounds

Sending the token using a custom header, example `X-Auth-Token`, works fine and is not truncated.

#### Related information 

* Programming language
```
Windows 10
Azure Functions Core Tools
Core Tools Version:       4.0.5611 Commit hash: N/A +591b8aec842e333a87ea9e23ba390bb5effe0655 (64-bit)
Function Runtime Version: 4.31.1.22191
Node v18.20.2
typescript v4
```

**Comment by ejizba** [comment]
Hi @exhaler this appears to be specific to static web apps. I tried with a standalone function app and wasn't seeing any problems. I believe this is actually related to https://github.com/Azure/static-web-apps/issues/34

**Comment by ejizba** [comment]
Closing in favor of static web apps bug
