### ISSUE TITLE
Allow for conditional triggering of input bindings

### ISSUE THREAD

**Issue by NathZ1** [Azure/azure-functions-nodejs-library#264]
#### Investigative information
Hi team, I have just refactored my TypeScript Function App to use the new v4 model - overall the codebase is much cleaner so thank you for the work to get this released!

The issues I have are 2 fold but both relate to the same thing:

1) I need to audit all access to data. This is difficult because the input binding that gets the data triggers immediately upon endpoint hit, but I have an auth check within the function code, so it would be great if the input binding could be conditionally triggered only when calling `context.extraInputs.get(sqlInput)`. This would ensure that all audit data was a true reflected of what users accessed.

2) Whenever I need to delete a row, I have to use an input binding with link to SP that deletes the data. Again, the issue is that this occurs immediately, before the user is authenticated, which may result in database changes that aren't meant to occur. Previously, I have got around this by having the function perform the auth check then call a second function that does the delete, but again - being able to conditionally trigger the input binding only would negate the need for this annoying double function pattern.

#### Repro steps
Example of issue number 1):
```
import { app, HttpRequest, HttpResponseInit, InvocationContext, input, SqlInput } from "@azure/functions"
import { isUserAuth } from "../utilities"

const sqlInput: SqlInput = input.sql({
    commandText: "SELECT * FROM dbo.ref_sites WHERE [GROUP] = @GROUP",
    commandType: "Text",
    parameters: "@GROUP={group}",
    connectionStringSetting: "SQLConnectionString"
})

async function getSites (request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`)

    const userAuth = await isUserAuth(request.headers.get('token') || '', request.query.get('group'), false)

    //I thought that this should only execute the input binding when userAuth === true, but it triggers immediately :(
    const sqlData = userAuth ? context.extraInputs.get(sqlInput) : undefined

    return {
        status: userAuth ? 200 : 403,
        headers: { 'content-type': "application/json" },
        body: JSON.stringify(sqlData)
    };
};

app.http('getSites', {
    methods: ['GET'],
    authLevel: 'anonymous',
    handler: getSites,
    extraInputs: [sqlInput]
})
```

Example of issue number 2):
```
import { app, HttpRequest, HttpResponseInit, InvocationContext, input, SqlInput } from "@azure/functions"
import { isUserAuth } from "../utilities"

const sqlInput: SqlInput = input.sql({
    commandText: "dbo.removeAdmissionInfo",
    commandType: "StoredProcedure",
    parameters: "@ENCNTRID={encntrid},@GROUP={group}",
    connectionStringSetting: "SQLConnectionString"
})

async function removeAdmissionInfo (request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    context.log(`Http function processed request for url "${request.url}"`);

    const userAuth = await isUserAuth(request.headers.get('token') || '', request.query.get('group'), false)

    //I thought that this should only execute the input binding when userAuth === true, but it triggers immediately :(
    if (userAuth) context.extraInputs.get(sqlInput)

    return {
        status: userAuth ? 200 : 403,
        headers: { 'content-type': "application/json" },
        body: userAuth ? JSON.stringify(request.body) : undefined
    };
};

app.http('removeAdmissionInfo', {
    methods: ['GET'],
    authLevel: 'anonymous',
    handler: removeAdmissionInfo,
    extraInputs: [sqlInput]
})
```

Is this something that can be configured now that we are GA for v4 model?

**Comment by ejizba** [comment]
Unfortunately you're correct and the input binding is retrieved before your code is ever executed. I think your workaround of two functions is a good one and the only other option I can think of is to use an sdk directly to get the input instead of an input binding

**Comment by NathZ1** [comment]
Thanks @ejizba for your reply. I have only used the SQL bindings in the past with Azure Functions as I was under the impression this was the preferred pattern to link Function App to Azure DB. What SDK would you recommend as an alternative?

**Comment by ejizba** [comment]
I think mssql is the most popular: https://www.npmjs.com/package/mssql

There's no strict preference, just differences for each. Bindings are certainly easier, but come with more restrictions. Using an sdk directly can be more complicated, but lets you do pretty much anything.

**Comment by NathZ1** [comment]
Thanks for your advice @ejizba. One final follow up before this can be closed as nothing actionable - If i use an SDK instead of bindings, wouldn't this introduce latency do to every api endpoint hit would result in a separate connection / disconnection to the SQL DB? (when compared to the bindings which keep the connection alive)

**Comment by ejizba** [comment]
We would actually recommend keeping a connection alive (also called "connection pooling"), even if you're using the sdk. In addition to latency which you mentioned, your app will have a limit on the number of connections you're allowed to have at once, so you don't want to be creating a connection for every execution.

Azure docs on connection limits: https://learn.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=javascript

mssql docs on connection pooling: https://github.com/tediousjs/node-mssql?tab=readme-ov-file#connection-pools

**Comment by NathZ1** [comment]
Thanks for that, I stumbled across those exact document a couple of days ago! I'm testing the perf difference side-by-side at the moment. 

Thanks again
