### ISSUE TITLE
enableHttpStream for nextjs apps

### ISSUE THREAD

**Issue by PaulTondeur** [Azure/azure-functions-nodejs-library#272]
A client of mine really wants their nextjs app deployed on Azure. I have followed the [nextjs on Azure instructions](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid).

Yet I need to make use of streaming http responses within my app. If I were to use plain Azure functions, I would need to have the following code executed:
```
const { app } = require('@azure/functions');
app.setup({ enableHttpStream: true });
```

The question is, how would we execute this from our nextjs app? Simply executing the code above results in runtime and build errors as it tries to resolve `@azure/functions-core`, which is only available on Azure architecture.

Would be great to get some pointers on how this needs to be resolved.

**Comment by ejizba** [comment]
@PaulTondeur Unfortunately, it looks like that scenario doesn't support Azure Functions:

> The following features of Static Web Apps are unsupported for Next.js with hybrid rendering:
> 
> - Select Azure services: Linked APIs using Azure Functions, Azure App Service, Azure Container Apps, or Azure API Management.

I've never seen this article before and I believe it was created by the static web apps team, so you would probably have better luck following up with them here: https://github.com/Azure/static-web-apps
