### ISSUE TITLE
Send a functionId in the metadata for registering a function 

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-nodejs-library#28]
This is to avoid a problem where multiple language workers are assigned to one function app. Following this change here: https://github.com/Azure/azure-functions-nodejs-worker/pull/634, the burden of generating a functionId for each function is relegated to the library instead of the worker to ensure consistent IDs for each function and support the new intelligent concurrency feature.

**Comment by ejizba** [comment]
Closing as this was only relevant for the draft PR. Non-draft PR here: https://github.com/Azure/azure-functions-nodejs-worker/pull/641
