### ISSUE TITLE
@handler not deinfed as param servicebustopictrigger

### ISSUE THREAD

**Issue by aj-ats** [Azure/azure-functions-nodejs-library#293]
I am building an TS funciotn model v4.  I defined my app.serviceBusTopic() below my funcoin.  I noticed that handler was required when i got a ts error 2345 (photo below) but not defined as that in the jsdoc nottation in @azure/funcitons/types/serviceBus.d.ts

I think it should be defined if it is nessacary. maybe microsoft thinks otherwise  or maybe im missinfomred and not seeing somehting.  anyway thanks for taking a look at this whoever does .  Ill outline rest below 

## reproduce 
Provide the steps required to reproduce the problem:
[1) set up a local service bus topic trigger model v4 **_in vscode_** 
](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-typescript)
2) paste example code into index.ts (or any funciton in the project)
``` typescript
import { app, InvocationContext } from '@azure/functions';

export async function serviceBusQueueTrigger1(message: unknown, context: InvocationContext): Promise<void> {
    context.log('Service bus queue function processed message:', message);
    context.log('EnqueuedTimeUtc =', context.triggerMetadata.enqueuedTimeUtc);
    context.log('DeliveryCount =', context.triggerMetadata.deliveryCount);
    context.log('MessageId =', context.triggerMetadata.messageId);
}

app.serviceBusQueue('serviceBusQueueTrigger1', {
    connection: 'MyServiceBusConnection',
    queueName: 'testqueue'
});
```
3) a red squiggle line should appear under the options {key : value} .  hover over it and notice how it dosnt show that handler is nessascary as a param 
![Screenshot 2024-08-26 134133](https://github.com/user-attachments/assets/bbffa694-358e-4c31-aeb2-ff5ddf204395)

#### Expected behavior
I belive the expected behavior should show handlers as a param.. if you think otherwise id love to understand why. 

thanks for maintaing this project microsoft

**Comment by aj-ats** [comment]
i think it would look cleaner and would be easier for devs if all the required objects are defined as parms

**Comment by ejizba** [comment]
> a red squiggle line should appear under the options {key : value} . hover over it and notice how it dosnt show that handler is nessascary as a param

Hi @aj-ats I'm a little bit confused by this. The screenshot says "Property 'handler' is missing", indicating that handler _is_ necessary.

**Comment by aj-ats** [comment]
ah I see I miss read sorry
