### ISSUE TITLE
Bump cookie dependency please - 0.6.0 causing npm audit to fail

### ISSUE THREAD

**Issue by NathZ1** [Azure/azure-functions-nodejs-library#301]
cookie 0.6.0 has a newly listed vulnerability - https://github.com/advisories/GHSA-pxg6-pf52-xh8x.

This causes `npm audit` to fail for current version of @azure/functions package.

Please bump cookie dependency to ^0.7.0.

**Comment by hallvictoria** [comment]
Addressed in https://github.com/Azure/azure-functions-nodejs-library/pull/310! Will close once a new release is out

**Comment by hallvictoria** [comment]
Version `4.6.0` has this change! Please update to that version to get the updated `cookie` version.
