### ISSUE TITLE
Vulnerability Report: Update cookie Package to Version 1.0.1

### ISSUE THREAD

**Issue by swapnilpakhale1998** [Azure/azure-functions-nodejs-library#313]
**Vulnerability Overview**
A vulnerability has been identified in the **'cookie'** package, which is currently used as a dependency. The issue is resolved in version **'1.0.1'**, but the project is still using version **'0.6.0'**. Updating the package version is necessary to address this vulnerability and enhance the security of the application.

**Action Required**
Please upgrade the **'cookie'** package from version **'0.6.0'** to version **'1.0.1'**.

**Additional Context**
The vulnerability in the **'cookie'** package affects the project, and the recommended fix is provided in version **'1.0.1'**.

**Comment by hallvictoria** [comment]
Hi @swapnilpakhale1998, thanks for reporting. Could you provide a link for this vulnerability?

I'm aware of the vulnerability in `0.6.0` and am in the process of doing a new release with `0.7.0`, but I couldn't find any information on a vulnerability for `cookie` versions under `1.0.1`.

**Comment by swapnilpakhale1998** [comment]
Hi **@hallvictoria,** thanks for your prompt response. Here’s the link to the vulnerability report: [OSV Vulnerability Report](https://osv.dev/vulnerability/GHSA-pxg6-pf52-xh8x).

The report indicates that the issue affects versions below 0.7.0 of the cookie package. I see that you've already upgraded to 0.7.0, which should effectively resolve this vulnerability.

Thanks for addressing it!

**Comment by hallvictoria** [comment]
Sounds good! Closing this as the vulnerability has been addressed
