### ISSUE TITLE
Provide a `Response` class for HTTP trigger functions

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-nodejs-library#36]
With a HTTP Trigger callback, we return an object with all the information for the response, from the body to status code, headers, etc.

This can feel a bit cumbersome, especially if you're coming from other API frameworks, such as Express or Fastify, where you have a `response` parameter and the function only returns the `body`.

Doing so would mean you could simplify code such as this:

```ts
app.get('route', (_, req) => {
  const headers: { [key of string]: string } = {}

  if (req.headers.has('accepts')) {
    const accepts = req.headers.get('accepts');
    if (accepts.indexOf('application/json')) {
      headers['content-type'] = 'application/json';
    }
  }

  return { headers, body: { foo: 'bar' } };
});
```

To:

```ts
app.get('route', (_, req, res) => {
  if (req.headers.has('accepts')) {
    const accepts = req.headers.get('accepts');
    if (accepts.indexOf('application/json')) {
      res.headers.add('content-type', 'application/json');
    }
  }

  return { foo: 'bar' };
});
```

Admittedly, this is the kind of thing that could be provided by a "higher level" wrapper around the low-level Functions API.

**Comment by ejizba** [comment]
My feeling is that a `res` object is more important in frameworks that rely on callbacks, where you frequently get a bunch of references to objects (err, req, res, etc.) passed as arguments. By contrast, I think a goal of the async/await pattern is to make inputs & outputs more intuitive and IMO `res` is clearly an output. We could mix & match qualities of both, but that gets confusing fast. For example, if I modify the body on the `res` argument, but return a different object from the promise, which takes priority?

What if we provide a `Response` class, but don't pass `res` as an argument? Aka your second example code would look like this:
```ts
app.get('route', (_, req) => {
  const res = new Response({ body: { foo: 'bar' } });
  if (req.headers.has('accepts')) {
    const accepts = req.headers.get('accepts');
    if (accepts.indexOf('application/json')) {
      res.headers.add('content-type', 'application/json');
    }
  }
  return res;
});
```

I've been modeling after undici a lot and they do have both `ResponseInit` (a barebones/flexible object) and `Response` (a more opinionated/helpful class), so this would be consistent. Of course users would be free to use this new class or just create their own.

**Comment by aaronpowell** [comment]
As I think about it more, I do think that the "res-as-param" design might be better addressed at a higher-level wrapper over the library, as that's the sort of thing that might be better tied to a framework like Express/Fastify/etc. and not really core to Functions.

Accepting the `Response` object as the return value from a Function might be a good idea, as it's clear that this is pretty low level, so using the raw types might be beneficial there. Would also save on having to write type definitions!

**Comment by ejizba** [comment]
Discussed during standup today. We will add a `Response` class, but we will not provide `res` as a parameter
