### ISSUE TITLE
Ability to provide the type information for params/query/body

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-nodejs-library#37]
These three parts of the HTTP request object are something that would be really useful to have type information provided to them, so that when they are used, we can get good type safety on their access.

I'd like to be able to write something like this:

```ts
type QS = {
  limit?: number
  offset: number
}
app.get('typed-qs', function<QS>(_, { query }) => {
  const limit = query.get('limit');
  const offset = query.get('offset');

  const invalid = query.get('invalid');  // this results in a TypeScript compiler error as `invalid` isn't a member of `QS`
});

type P = { id: string };
app.get('person/{slug}', function<P>(_, { params }) => {
  const { slug } = params;

  const invalid = params.invalid; // this results in a TypeScript compiler error as `invalid` isn't a member of `P`
});

type B = { id: string };
app.post('person', async function<B>(_, req) => {
  const body = await req.json(); // json method return Promise<B>
});
```

**Comment by ejizba** [comment]
Generic types can get messy fast, especially if we're asking for 3 different types here (query, params, and body). I would probably suggest a user create their own HttpRequest type that extends our HttpRequest and just replace it in the type signature:

```typescript
interface CustomHttpRequestType extends HttpRequest {
    json(): Promise<{ id: string }>;
}

app.get('httpTrigger1', async (context: InvocationContext, request: CustomHttpRequestType) => {
    const body = await request.json();
});
```

**Comment by aaronpowell** [comment]
Could we do a single generic argument that represents the `body` of the request, as that is likely the most used type by developers, and if they want others, then it should be customizable like you suggest.

**Comment by ejizba** [comment]
This just came up again (https://github.com/Azure/azure-functions-nodejs-library/pull/286), so I did some digging to validate why none of the community does this either. Here's a good comment that explains why: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36868#issuecomment-512989650
