### ISSUE TITLE
Clarify host vs npm package versions in readme

### ISSUE THREAD

**Issue by blowsie** [Azure/azure-functions-nodejs-library#59]
The official docs suggest we should be using v4.x since v3.x is end of life.
![image](https://user-images.githubusercontent.com/308572/216369347-147b4541-9913-4b45-b0d8-f651e4fda544.png)

I discovered this after using this repo which suggests we should be using v3.x

Which one is correct? I assume the main docs?
https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-javascript#migrating-from-3x-to-4x

**Comment by ejizba** [comment]
Hi @blowsie they are both correct. The azure functions host runtime and the node.js npm package versions are individual unrelated versions that just happen to be near in each other in number. Host runtime v4 and npm package v3 are the recommended verisons

I can leave this issue open to clarify in our readme

**Comment by blowsie** [comment]
Excellent, thank you for clearing that up, perhaps an oversight on my part.
