### ISSUE TITLE
Auto-generated Timer Function Should Use Timer Type Instead of `any` in TypeScript

### ISSUE THREAD

**Issue by PCOffline** [Azure/azure-functions-nodejs-library#63]
Instead of using the `Timer` type exported from `@azure/functions`, a Timer-triggered function generated by the az cli or VSCode extension uses `any`:
```ts
import { AzureFunction, Context } from '@azure/functions';
const timerTrigger: AzureFunction = async (context: Context, myTimer: any): Promise<void> => {
```
should become
```ts
import type { AzureFunction, Context, Timer } from '@azure/functions';
const timerTrigger: AzureFunction = async (context: Context, myTimer: Timer): Promise<void> => {
```

**Comment by ejizba** [comment]
We originally didn't do this when `Timer` was added to `@azure/functions` because it would cause a build error for users who created a timer trigger with older versions of `@azure/functions` in their project. At this point it's probably been long enough that we can add `Timer` to the template with minimal impact

**Comment by PCOffline** [comment]
Hey are there any updates on this?

**Comment by PCOffline** [comment]
Bumping this!

**Comment by PCOffline** [comment]
Hey @ejizba, any updates on this?

**Comment by ejizba** [comment]
Hi @PCOffline this is not a priority at the moment. Any particular reason you're following this for updates? Do you create timer triggers from a template often? I would expect this to be a feature used rarely once you set up your app. Our priority for new apps at the moment is programming model v4, and those templates already have timer types.

If you want a quicker resolution, you're welcome to look into filing a PR on the templates repo here:
https://github.com/Azure/azure-functions-templates

**Comment by PCOffline** [comment]
I do find myself creating timer functions with that template, but in the case of v4, I see it really isn't a necessity. Thanks for the quick response!

**Comment by castrodd** [comment]
I merged [this PR](https://github.com/Azure/azure-functions-templates/pull/1489) that makes the change requested by @PCOffline. Closing this issue as resolved.
