### ISSUE TITLE
Model V4 will not run with a local emulator in WSL via VSCode

### ISSUE THREAD

**Issue by tyler-the-freeman** [Azure/azure-functions-nodejs-library#66]
It does not appear that Model V4 functions can be run locally inside of WSL, it is not correctly detecting functions when attempting to launch. I am not sure if this is an issue with Azure Functions Core Tools or the NodeJS library. 

#### Investigative information

Please provide the following:

- Timestamp: N/A
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

This is an issue running with a local emulator.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Launch VSCode in WSL
2. Install Azure Functions, Azure Functions Core Tools and Azurite via VSCode Extensions
3. Via the Azure Functions extension, create a new function in the local workspace
4. Select folder > JavaScript > Model V4 > HTTP Trigger > httpTrigger1
5. Launch Azurite in VSCode via "Azurite: Start" 
6.  Under Workspace in the Azure Extension select "Start debugging to update this list...." 
7. Choose "Local Emulator" to add "AzureWebJobsStorage": "UseDevelopmentStorage=true" to the local.settings.json file.

#### Expected behavior

Example HTTP Trigger function launches, listening on http://localhost:7071/api/httpTrigger1

#### Actual behavior

Azure Functions Core Tools Launches, reports "No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)."

Running with "func start --verbose" shows no functions are detected.

#### Known workarounds

Currently only able to get this running on Windows without WSL

#### Related information 
N/A

**Comment by ejizba** [comment]
Hi @tyler-the-freeman can you verify your version of core tools? You will need v4.0.4915 or higher

If that doesn't work, can you double check that your `local.settings.json` has `AzureWebJobsFeatureFlags` set to `EnableWorkerIndexing` (this setting is going away very soon, but is still required as of today).

**Comment by tyler-the-freeman** [comment]
@ejizba You know what, the core tools version is totally what it is, didn't even think to look at the versions being different. Looks like I am only able to get up to version 4.0.4895 on Ubuntu 20.04 and 22.04 via apt. The windows install version is up to 4.0.5030, which is why it was working there. 

Doing a manual install via the zip [here](https://github.com/Azure/azure-functions-core-tools/releases) and I am able to get it running. Appreciate the help.
