### ISSUE TITLE
Add hooks api to framework package

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-library#7]
At the moment hooks are only exposed in the core api. However, we want the new programming model packages to wrap the core api and expose a "nicer" version of the hooks api (better intellisense, maybe better naming, full docs, etc.)

**Comment by aaronpowell** [comment]
_This builds on some of the ideas proposed in https://github.com/Azure/azure-functions-nodejs-worker/issues/664_

Here's an idea I have for how we could do middleware:

```js
import { app } from "@azure/functions";

app.get("home", () => ({ body: "Hello World" });

app.middleware({
  hookName: "preInvocation",
  hook: (context) => {
    //do stuff
  }
});

app.preInvocation(context => {
  //do stuff
});

app.middleware({
  hookName: "preInvocation",
  filter: "httpTrigger"
  hook: () => {}
});

app.middleware({
  hookName: "preInvocation",
  filter: (context) => context.trigger.url.contains("foo"),
  hook: () => {}
});
```

There's probably a bunch of additional permutations that we could support to make it more akin to the kind of middleware like you would come across in web frameworks, but also support the scenarios of having different trigger types within your application.

**Comment by aaronpowell** [comment]
Also, once https://github.com/Azure/azure-functions-nodejs-worker/issues/665 is implemented, we can make the types available for the `context` of a hook callback richer so that it's possible for us to know what's available on properties such as `invocationContext`.
