### ISSUE TITLE
Uncatchable exception parsing formData

### ISSUE THREAD

**Issue by alexhudson** [Azure/azure-functions-nodejs-library#70]
This might just be a really basic thing - but I feel like I've bumped into an issue right at the start of trying out the new V4 API. I'm just trying to parse some data out of a POST call, and return useful information to the caller if the right parameters are not present. I've followed the documents but there is no exemplar version of the code, and the behaviour seems wrong to me. I'm getting 500s for calls that are not quite right, but I don't want these to log out as failures - as they will then show up in the monitoring as application failures. I want the app to handle these cases.

#### Repro steps

I have a basic function that works until I try to parse POST data. It looks like this:

```typescript
export async function TestFunction(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    let body;
    try {
        body = await request.formData();
    } catch (e: any) {
        return {
            status: 400,
            body: 'Cannot parse form body'
        }
    }
}
```

#### Expected behavior

I expect the API to return a 400 if there is no POST data and/or the data is malformed?

#### Actual behavior

The API returns an HTTP 500 response.

Error output in logs:

```
Exception: Request.formData: Could not parse content as FormData.
Stack: TypeError: Request.formData: Could not parse content as FormData.
    at webidl.errors.exception (C:\Users\...\node_modules\undici\lib\fetch\webidl.js:13:10)
    at Request.formData (C:\Users\...\node_modules\undici\lib\fetch\body.js:468:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5).
```

The exception doesn't appear to be in a place where it can be caught.

#### Known workarounds

None.

**Comment by ejizba** [comment]
Hi @alexhudson it seems to be working for me. Here I am hitting a breakpoint in the catch block:
![Screenshot 2023-03-24 at 1 57 18 PM](https://user-images.githubusercontent.com/11282622/227638505-1b00e7ef-7498-4967-9315-852e725248d3.png)

And here's the result of my request showing a 400 response:
<img width="485" alt="Screenshot 2023-03-24 at 1 57 26 PM" src="https://user-images.githubusercontent.com/11282622/227638512-c921a3da-7b1d-4af4-8d41-72e0285af74b.png">

Can you double check which versions of `@azure/functions` and `undici` you are on and let me know?

**Comment by alexhudson** [comment]
I've tried it again this morning and of course it seems to work.

I'm wondering if there was some issue with the Typescript not actually building into the JS that was being run - if I remove the try/catch, I do get the backtrace listed. Annoyingly it's not rooted in my test function but I guess that's the async.

Sorry!
