### ISSUE TITLE
Model v4 - Hot reloading not working

### ISSUE THREAD

**Issue by philhagger** [Azure/azure-functions-nodejs-library#75]
I am testing out the new Model v4 functions using nodejs (not TypeScript). I am using VSCode and in previous versions `npm start` would run `func start` which in turn would enable hot reloading. I could edit files, save, and the changes would apply.

Currently I have to stop the running process after every change, then restart it to get the new code to apply...

After every save in vscode I am getting `Worker process started and initialized.` Which previously indicated that the new code was in play.

### package.json
```{
  "name": "fa-modelv4",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/functions": "^4.0.0-alpha.9"
  },
  "devDependencies": {},
  "main": "src/functions/*.js"
}
```
### npm start

```node ➜ /workspaces/FA-Modelv4 (master) $ npm run start

> fa-modelv4@1.0.0 start
> func start


Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396

[2023-03-29T10:26:46.998Z] Worker process started and initialized.

Functions:

        httpTrigger1: [GET,POST] http://localhost:7071/api/httpTrigger1
```

Any thoughts?

**Comment by ejizba** [comment]
This will require a fix in the host. I've filed an issue on them here: https://github.com/Azure/azure-functions-host/issues/9185

**Comment by ejizba** [comment]
This was fixed in host v4.21 which was included in core tools v4.0.5198

**Comment by rafaelgrilli92** [comment]
@ejizba, it's not working for me. Is hot reload an out-of-the-box feature or does it need to be configured?
Node - Typescript - Model v4
Core Tools Version: 4.0.5390
Function Runtime Version: 4.25.3.21264

**Comment by ejizba** [comment]
@rafaelgrilli92 should work out of the box yeah. Please file a new issue with your repro steps and we'll take a look
