### ISSUE TITLE
v4 doesn't detect my functions

### ISSUE THREAD

**Issue by Tschonti** [Azure/azure-functions-nodejs-library#78]
I just switched my existing project to the new programming model v4 using [this migration guide](https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-upgrade-v4?tabs=vs-code-set-indexing-flag%2Cv4). I love the idea that I can structure my directories and files as I want, but it doesn't seem to work.

#### Repro steps

Provide the steps required to reproduce the problem:

1. create functions inside nested folders. My folder structure:
```
src
+---functions
|   +---criteria
|   |   |   create.ts
|   |   |   getall.ts
|   |   |   getone.ts
|   |   |
|   |   \---types
|   |           createCriteria.dto.ts
|   |
|   +---events
|   |       getall.ts
|   |
|   \---ratings
|       |   create.ts
|       |   getcriteria.ts
|       |   rateone.ts
|       |
|       \---types
|               createRating.dto.ts
|
\---lib ...
```
All my functions look something like this:
```typescript
import { HttpRequest, HttpResponseInit, InvocationContext, app } from '@azure/functions'

export const getCriteria = async (req: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> => {
  ...
  return { body: ... }
}

app.http('ratings-getcriteria', {
  methods: ['GET'],
  route: 'ratings/{id}',
  handler: getCriteria
})
```
2. set the main property in package.json to `dist/src/functions/**/*.js` (yes, there is an src directory inside dist)
I also tried assigning all the http routes in one index.ts file in /functions and refenrece that one file in packege.json, but that didn't work either.

#### Expected behavior
My functions are recognised and mapped to HTTP routes

#### Actual behavior

I get the following warning:

No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

Sorry if this isn't the right place to ask (this probably isn't an issue with the package, I just couldn't figure out how to use it) but there is very little information about this version right now.

**Comment by ejizba** [comment]
Hi @Tschonti yes this is a perfect place to file this issue - thanks for trying out the new model!

A couple ideas:
1. You mentioned setting "main" to `dist/src/functions/**/*.js`. Can you confirm your tsconfig is outputting to "dist" instead of "lib" or "out"?
2. Are you testing locally or in Azure? Locally you need core tools v4.0.5095 or higher
3. Did you add the setting `AzureWebJobsFeatureFlags` set to `EnableWorkerIndexing`? The steps should be covered in the upgrade guide, but from my own experience it's easy to forget this setting 😅

**Comment by Tschonti** [comment]
@ejizba My core tools version was 4.0.4895... but now it works, thank you so much!
