### ISSUE TITLE
Ensure v4 model compatibility with Static Web Apps

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-library#80]
This should hopefully "just work", but we should test some end-to-end static web app scenarios before GA.

**Comment by diberry** [comment]
Current issues [Node JS function v4 · Issue #1139 · Azure/static-web-apps (github.com)](https://github.com/Azure/static-web-apps/issues/1139)

**Comment by ejizba** [comment]
I tried this today. I put up a PR to fix the VS Code problems here: https://github.com/microsoft/vscode-azurefunctions/pull/3721

The other problem is you can't set `AzureWebJobsFeatureFlags` to `EnableWorkerIndexing` in SWA, but the flag requirement is going away - it just hasn't made it to all regions yet. I tested in West US 2 and got it working.

**Comment by offbeatful** [comment]
Nice to see some traction here! When is it expected to work without the flag?

**Comment by ejizba** [comment]
Like I said it's already rolled out in some regions - you can use "West US 2" today. For the rest of the regions, I would guess we finish in the next month or so.

**Comment by offbeatful** [comment]
Yes, I can confirm it is working in West US 2. Thank you!

**Comment by ejizba** [comment]
The flag should be enabled by default in all regions at this point

**Comment by feuersteiner** [comment]
sorry to comment here.

I am having trouble running functions v4 (typescript) with SWA cli (the cli is only compatible at node <=16, and the functions node >=18). I haven't reached the deployment problem just yet ... because the whole thing is not running on my local machine. is there a blog post on this? best practices? because for now, it feels like a little bit disorienting to not find any documentation about this transition. Thanks again for the effort!

**Comment by ejizba** [comment]
@feuersteiner I think the swa cli is supposed to work with Node18 now. See their [v1.1.4 release](https://github.com/Azure/static-web-apps-cli/releases/tag/v1.1.4) and [this issue](https://github.com/Azure/static-web-apps-cli/issues/663) for details. You definitely need node 18 to work with the new model, so if you can't get node 18 working with the swa cli I'd recommend following up in [their repo](https://github.com/Azure/static-web-apps-cli)

**Comment by feuersteiner** [comment]
> @feuersteiner I think the swa cli is supposed to work with Node18 now. See their [v1.1.4 release](https://github.com/Azure/static-web-apps-cli/releases/tag/v1.1.4) and [this issue](https://github.com/Azure/static-web-apps-cli/issues/663) for details. You definitely need node 18 to work with the new model, so if you can't get node 18 working with the swa cli I'd recommend following up in [their repo](https://github.com/Azure/static-web-apps-cli)

thanks a lot for your message @ejizba !! was easy to get lost in outdated documentation (even on the site of the sea-cli stating that it only supports <=16).
Tried what you said on a fresh node 18 install and it worked like a charm 🙏🙏
