### ISSUE TITLE
Make v4 entry point failures more obvious

### ISSUE THREAD

**Issue by adamstoffel** [Azure/azure-functions-nodejs-library#85]
UPDATE by @ejizba: This change has been included in host 4.25. It is a *breaking change* for model v4 as some errors that were previously ignored will now block your app as an error.

### Workaround to get old behavior

You can set the app setting `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` to `false` if you want the old behavior. However, we actually recommend setting this to `true` for all v4 apps. For more information, see the [App Settings reference](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_node_block_on_entry_point_error)
________

#### Investigative information

- Timestamp: 2023-04-17T20:18:05.2026993Z
- Function App name: (private)
- Function name(s) (as appropriate): (all)
- ~Invocation~ Host Instance ID: 16717bc2-cc29-4b43-815b-db2781f9ef3f
- Region: northcentralus

#### Repro steps
1. Write a simple node v4 functions app which throws an Error in the entry point.
2. Run the app locally; see that the error is show in the console, although the runtime ignores the error and proceeds.
3. Deploy the app to cloud Azure Functions with Application Insights; see that the error is unable to be found.

#### Expected behavior
The error message should have been exposed in Application Insights. Additionally, it would be helpful to expose the full exception object, not just the message.
As a potential configuration option, startup should fail completely if an entry point fails to execute.

#### Actual behavior
When running functions locally, any exception which is thrown while executing entry point files is exposed in the console. E.g. see the first line below:
```bash
Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396
[2023-04-17T20:02:47.709Z] Worker was unable to load entry point "dist/entryPoints/**/*.js": <THROWN EXCEPTION MESSAGE IS SHOWN HERE>
[2023-04-17T20:02:50.722Z] Workers Directory set to: C:\Program Files\Microsoft\Azure Functions Core Tools\workers
...
[2023-04-17T20:02:51.511Z] 0 functions loaded
...
[2023-04-17T20:02:51.682Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

When deploying this same code to cloud Azure Functions with Application Insights configured, the first trace which is emitted is:
```
4/17/2023, 1:18:05 PM TRACE
Workers Directory set to: /azure-functions-host/workers
Severity level: Verbose
```

Doing a search for `Worker was unable to load entry point` in Application Insights returns no results.

#### Known workarounds
None

**Comment by ejizba** [comment]
Hi @adamstoffel totally agree with the desired behavior and I can repro on my own apps. Unfortunately I'm not aware of any workarounds, but we'll look into this

**Comment by jurijsk** [comment]
Facing the same issue with "No job functions found.". In my case something breaks during the job functions discovery, and I pinpointed the error to the import of `@azure/storage-blob` but even that is not certain, because sometimes it fails, the other times it's not. I've described the the problem here: https://github.com/Azure/Azure-Functions/issues/2368

**Comment by aangelisc** [comment]
Just to add to this issue, I'm also seeing something similar to @jurijsk when attempting to use the `applicationinsights` Node.js SDK. Running the below code causes the function to no longer be found, despite the fact it is detected.

```
import * as ai from "applicationinsights";
import { AzureFunction, Context } from "@azure/functions";

ai.setup().start();
const timerTrigger: AzureFunction = async function (
  context: Context,
  myTimer: any
): Promise<void> {
  context.log("Timer function processed request.");
};

export default timerTrigger;
```

**Comment by floriankoch** [comment]
@ejizba   like @aangelisc   i also got  an error when i try to import `applicactioninsights`
I try this with the durable functions variant
`[2023-05-18T18:09:42.742Z] WARNING: Failed to detect the Azure Functions runtime. Switching "@azure/functions" package to test mode - not all features are supported.
[2023-05-18T18:09:42.742Z] WARNING: Skipping call to register function "sslmonOrchestrator" because the "@azure/functions" package is in test mode.
...
`
any idea what causing this and how to fix?

**Comment by ejizba** [comment]
@floriankoch please see this issue for your specific issue and a suggested workaround: https://github.com/Azure/azure-functions-nodejs-worker/issues/685#issuecomment-1560262614

**Comment by floriankoch** [comment]
@ejizba   thx will do
