### ISSUE TITLE
Add SQL trigger support to v4 model

### ISSUE THREAD

**Issue by lucyzhang929** [Azure/azure-functions-nodejs-library#88]
More information about SQL Bindings can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql?tabs=in-process%2Cextensionv4&pivots=programming-language-csharp).

**Comment by ejizba** [comment]
Added input and output binding support. I'm hesitant to add trigger support while it's still in preview, especially considering users have a workaround with our `generic` support.

I'd be willing to reconsider if we have users asking for it (upvotes/comments on this issue would be best), otherwise we should be able to do it as soon as it GA's. Feel free to ping us as the GA date approaches

**Comment by andreasbhansen** [comment]
Any thoughts on adding support for SQL triggers now a half-ish year later, @ejizba? Are there still issues with this functionality which blocks the implementation into @azure/functions?

**Comment by ejizba** [comment]
It's a question of priority against our other work, not anything blocking it necessarily. I was primarily waiting for the SQL trigger to go GA, but as far as I can tell the [docs](https://learn.microsoft.com/azure/azure-functions/functions-bindings-azure-sql-trigger?tabs=isolated-process%2Cportal&pivots=programming-language-javascript) still list it as preview. If GA won't be for a long time or if we get sufficient user feedback asking for it, we could add it before GA. But to be honest @andreasbhansen you're the first person to ask for it (excluding Lucy who is on the team that developed the sql stuff 😉)

**Comment by lucyzhang929** [comment]
@ejizba GA for SQL trigger will be very soon! We are currently waiting for a new extension bundle version to be released which will contain our GA bits. Will update here once we are officially GA.

**Comment by lucyzhang929** [comment]
@ejizba The [SQL trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-trigger?tabs=isolated-process%2Cportal&pivots=programming-language-javascript) is now generally available!

**Comment by ejizba** [comment]
Fyi @andreasbhansen @lucyzhang929 we just released v4.4.0 with SQL trigger support
