### ISSUE TITLE
Phantom functions appear when starting the v4 TypeScript app

### ISSUE THREAD

**Issue by shaipetel** [Azure/azure-functions-nodejs-library#96]
#### Repro steps

Provide the steps required to reproduce the problem:

- create a v4 TypeScript project, using Node v18
- add a function func1 http trigger in a file called func1.ts
- add a function func2 http trigger in a file called func2.ts
- build, start the app
- delete the func2.ts file
- build, start the app

#### Expected behavior
In first launch - both functions show up. in second launch, only func2

#### Actual behavior

func2 still shows up since the file func2.js is never removed from the dist folder

#### Known workarounds

- I added a cleanup call before the build starts

#### Related information 

* Programming language used TypeScript

**Comment by ejizba** [comment]
Hi @shaipetel we recently added a clean script to the default project templates in [VS Code](https://github.com/microsoft/vscode-azurefunctions/pull/3654) and [core tools](https://github.com/Azure/azure-functions-core-tools/pull/3339). I think both changes have been released by now, although it may have been pretty recently. Try those out and let us know if you still want any changes

**Comment by shaipetel** [comment]
My project is 2 weeks old so maybe added after, but yeah essentially that's what I ended up doing.
